### ISSUE TITLE
Show all results on 'table' view of categorical histograms

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/glam#1085]
We've had a user (@pbz) ask in Slack to be able to see the long tail of buckets in a [categorical histogram](https://glam.telemetry.mozilla.org/firefox/probe/external_protocol_handler_dialog_context_scheme/explore). (We're currently only showing the top 10 and then combining the rest into "other".)

Fitting all of the categories onto the graph would be tough, but it'd be easy to display them all on the 'table' view, at least.

**Comment by hsivonen** [comment]
It would help to even have a way to ask for all instead of having to check the box for each category individually.

**Comment by rafrombrc** [comment]
Yes, we'll add a 'select all' to the dropdown and also include the dropdown selector on the "table view" page.
