### ISSUE TITLE
"Key" dropdown not available in nightly for qm_quota_info_load_time_v0

### ISSUE THREAD

**Issue by tdsmith** [mozilla/glam#1097]
I noticed while evangelizing Glam at https://bugzilla.mozilla.org/show_bug.cgi?id=1683102 that the qm_quota_info_load_time_v0 probe display in Glam supports viewing this keyed histogram by key in beta and release but not in nightly and I'm not sure why; there's no "key" dropdown.

~The probe may have recently expired in current nightly.~ It expires in the next nightly.

**Comment by rafrombrc** [comment]
Close bc this probe has expired, if we find a new one w this issue we'll open another ticket.
