### ISSUE TITLE
Ability to get a pushlog range from the history view

### ISSUE THREAD

**Issue by mstange** [mozilla/glam#1124]
(Migrated from https://github.com/mozilla/telemetry-dashboard/issues/248 )

It should be possible to select a range in the history graph and obtain a URL for a pushlog ([example](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=c4186bb32c302ec2c82b3b0323af828ccebe0b48&tochange=bd7c35b7e234712f94f6dbb755ad983c1db8b07b)) that lists the changes that landed in the selected range.

Motivation:

When looking at the historical graph of a telemetry probe, the main question on my mind is:
"Did anything change, and if so, why?"
The "why" is currently rather cumbersome to track down. There are [manual steps](https://github.com/mozilla/telemetry-dashboard/issues/248#issuecomment-728315593) to get there, but since this is such a central workflow, we should automate as much of the process as we can.

This probably needs to implemented separately per product. For Gecko + Firefox Desktop, you can get the revision from the build ID using a rest query to https://buildhub.moz.tools/ (@wlach knows the specifics) and then build the pushlog URL. For Fenix, the user probably wants to see a commit log on github.

**Comment by wlach** [comment]
> (Migrated from [mozilla/telemetry-dashboard#248](https://github.com/mozilla/telemetry-dashboard/issues/248) )

> This probably needs to implemented separately per product. For Gecko + Firefox Desktop, you can get the revision from the build ID using a rest query to https://buildhub.moz.tools/ (@wlach knows the specifics) and then build the pushlog URL. For Fenix, the user probably wants to see a commit log on github.

The fenix commit log won't contain web platform specific changes (which I think are 99% of the time the thing causing regression or improvements), since those are coming from GeckoView. To get a range for that, we'd probably want to use buildhub again (or something like it), which unfortunately does not yet index fenix builds and their dependencies. I had a similar issue with mozregression and filed [bug 1622948](https://bugzilla.mozilla.org/show_bug.cgi?id=1622948) to track adding that feature.

**Comment by mstange** [comment]
True, for Fenix I would want both - the Gecko pushlog range for Gecko probes, and the Fenix github commit range for Fenix front-end probes.

Edit: Actually, both would be useful regardless of which probe it is. Gecko changes can affect Fenix probes, and Fenix changes can affect Gecko probes.
