### ISSUE TITLE
De-emphasize inactive probes in search results

### ISSUE THREAD

**Issue by mstange** [mozilla/glam#1125]
I was using the search field in GLAM to find probes about GC pause times, and one of the top results showed me an inactive probe without any data.

Steps to reproduce:
 1. Go to https://glam.telemetry.mozilla.org/.
 2. Enter "gc pause" in the search field.

Expected results:
I should see the most relevant results first. In this case this would be "gc_max_pause_ms_2". Active probes should be ranked higher than inactive probes, and ideally the search result list should be annotated with "active" / "inactive".

Actual results:
At the moment, number 1 is "cycle_collector_max_pause", and number 2 is "gc_max_pause_ms".
"cycle_collector_max_pause" is somewhat related, but CC is strictly speaking not GC.
More importantly, "gc_max_pause_ms" is an inactive probe and doesn't show any data.
Its replacement, "gc_max_pause_ms_2", is at the bottom of the list.

**Comment by mstange** [comment]
The same happens if you search for "delay". The first five results (which take up 75% of the search result screen estate) are all inactive probes without data.

**Comment by wlach** [comment]
Note that "inactive" actually means "expired" in the case mentioned: https://probes.telemetry.mozilla.org/?search=gc_max_pause_ms&view=detail&probeId=histogram%2FGC_MAX_PAUSE_MS

I.e. we're not collecting any data for this, and haven't been for quite some time.
