### ISSUE TITLE
Small regressions are harder to see, compared to the old dashboard

### ISSUE THREAD

**Issue by mstange** [mozilla/glam#1126]
Compare these two graphs:
Old: https://mzl.la/3p9QHhw
New: https://glam.telemetry.mozilla.org/firefox/probe/a11y_instantiated_flag/explore?activeBuckets=%5B%220%22%2C%221%22%5D&process=parent&ref=20201213213752&timeHorizon=ALL

Both are showing the same probe for the same range, 79 to 86.
In the old graph I can clearly see an uptick in "True percentage" during 80. In the new graph I cannot see it - the increase looks much more gradual in the new graph.

Old:
<img width="1412" alt="Screen Shot 2021-01-21 at 12 58 06 PM" src="https://user-images.githubusercontent.com/961291/105391735-69c52480-5be8-11eb-88dc-8dfc27996b79.png">

New:
<img width="502" alt="Screen Shot 2021-01-21 at 12 58 24 PM" src="https://user-images.githubusercontent.com/961291/105391746-6df14200-5be8-11eb-90bb-24f2dd100b8c.png">

**Comment by rafrombrc** [comment]
First step here is to dig in to try to understand why this blip didn't show up in GLAM. @robhudson to advise on how to see this in a local env (since it's paged out of live GLAM).

**Comment by rafrombrc** [comment]
We've dug in to this and now understand why this difference exists: GLAM normalizes the aggregations by client id, so a single client weighs equally to all other clients, regardless of how many samples that client sends. TMO measurement dashboard does not, so if a single client sends a ton of pings then that client will impact the distribution more heavily. This normalization is what obscures the changes.

We're currently engaged in a gap analysis to understand this and other differences btn TMO and GLAM, and will need some Data Science support to know what all of the implications are here. More on this soon.

**Comment by Iinh** [comment]
We're trying to figure out the most optimal way to show non-normalized aggregations in GLAM, in addition to the current data that's aggregated by client id. Updates on this issue will be posted in #1929.

**Comment by edugfilho** [comment]
The solution to this will be implemented in #2085. 
@mstange please subscribe to the issue above to continue to receive updates on this issue!
Closing this ticket as a duplicate
