### ISSUE TITLE
The summary table is cramped

### ISSUE THREAD

**Issue by mstange** [mozilla/glam#1135]
On [the page for the `content_frame_time_reason` probe](https://glam.telemetry.mozilla.org/firefox/probe/content_frame_time_reason/explore?activeBuckets=%5B%22OnTime%22%2C%22SlowComposite%22%2C%22MissedCompositeLong%22%2C%22MissedCompositeMid%22%2C%22MissedComposite%22%2C%22MissedCompositeLow%22%2C%22NoVsyncNoId%22%2C%22NoVsync%22%5D&process=parent&ref=20210115035053), the Summary table on the right doesn't have enough space for the reasons.

Many rows show "MissedC...".

<img width="1328" alt="Screen Shot 2021-01-26 at 12 33 33 PM" src="https://user-images.githubusercontent.com/961291/105881830-f863e800-5fd2-11eb-99ea-64ecca9c92fa.png">

**Comment by Iinh** [comment]
Closed via #1339.
