### ISSUE TITLE
GLAM search seems to not find obvious probes

### ISSUE THREAD

**Issue by fbertsch** [mozilla/glam#1138]
Here is an example: search for "tab open count". Below is the response from GLAM. In that entire list, the probe `browser.engagement.tab_open_event_count` is not present:
![Screenshot_2021-01-27 GLAM Glean Aggregated Metrics Explorer](https://user-images.githubusercontent.com/20819040/106000085-6d3f2c80-607c-11eb-9850-9934766d65a6.png)

If we then do that same search in the probe-dictionary, where it appears third (behind some other good options for the search):
![Screenshot_2021-01-27 Firefox Probe Dictionary - Find Probes](https://user-images.githubusercontent.com/20819040/106000124-792aee80-607c-11eb-89be-cc5e8393ce7a.png)

**Comment by robhudson** [comment]
Fixed in https://github.com/mozilla/glam/pull/1139
