### ISSUE TITLE
"404: No data found for the selected dimensions." for "flash_plugin_area" etc

### ISSUE THREAD

**Issue by MatsPalmgren** [mozilla/glam#1149]
**STEPS TO REPRODUCE**
1. go to https://glam.telemetry.mozilla.org/
2. type "flash" in the search box
3. click on one of the completions from the menu. e.g. "flash_plugin_area"

**ACTUAL RESULTS**
"404: No data found for the selected dimensions."
It appears most of the menu items matching "flash" contains no data, fwiw.

**EXPECTED RESULTS**
Some data.  Alternatively, if data for "flash_plugin_area" no longer exist it should not show up in the completion menu.

**Comment by robhudson** [comment]
This is fixed but not deployed yet. Production push coming soon.

**Comment by robhudson** [comment]
This is now deployed.

**Comment by rafrombrc** [comment]
Inactive probes now show a prominent "inactive" label in the search dropdown.
