### ISSUE TITLE
Odd looking display on browser_engagement_total_uri_count_normal_and_private_mode

### ISSUE THREAD

**Issue by chutten** [mozilla/glam#1181]
URL: https://glam.telemetry.mozilla.org/firefox/probe/browser_engagement_total_uri_count_normal_and_private_mode/explore?aggregationLevel=version&channel=release&process=parent&ref=85&timeHorizon=QUARTER

Was looking at this scalar on release and it doesn't have trend lines:

![image](https://user-images.githubusercontent.com/1123376/108073475-15ba2e00-7036-11eb-9376-1e14ab630c2b.png)

Not sure what's going on here, should be collected since 84, so there ought to be data.

**Comment by Iinh** [comment]
Hi @chutten just wondering if this is still an issue for you? If yes could you let us know your browser and operating system? (we suspect that there might be a display issue using GLAM in Firefox Nightly on Linux)

**Comment by chutten** [comment]
The URL looks fine to me on Nightly on Linux today, so I guess the problem's solved? Here's hoping : D
