### ISSUE TITLE
Update explore view for new probes with only 1 histogram

### ISSUE THREAD

**Issue by robhudson** [mozilla/glam#1187]
For new probes added it takes GLAM 2 histograms worth of data to show a chart. With only 1 histogram the explore page could be a bit more explanatory or show some data. The usual chart view requires multiple points to show the over-time chart but we could show something else here until more data flows in.

**Comment by robhudson** [comment]
In 32a6ab9 the chart was fixed to show when there are 2 data points so it doesn't look broken. We can still do something extra when only 1 data point is there.

**Comment by rafrombrc** [comment]
Possibly an opportunity to revisit the UI to be able to support data validation for new probes.

**Comment by Iinh** [comment]
Do we know if there's a way to find probes that only have 1 histogram so far in prod? I'm currently using some test data to reproduce the Explore page with 1 data point locally, but I want to make sure that this issue also looks the same in production.

In case anyone's curious, this is how the page looks like with just 1 data point:

<img width="955" alt="Screen Shot 2022-03-09 at 11 52 09 AM" src="https://user-images.githubusercontent.com/28797553/157490474-5ebee9ff-0bff-4aa6-aa16-29dbf02009e1.png">
