### ISSUE TITLE
Need to know which Firefox Telemetry probes are being used (in GLAM)

### ISSUE THREAD

**Issue by chutten** [mozilla/glam#1193]
(See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1693822)

For FOG Migration it'd be really handy to have a quick way to check if a given Firefox Telemetry probe is ever being used.

BQ can tell us the SQL folks are running, and we can grep them for column names in telemetry.main. But what if someone's diligently keeping an eye on the health of their probe via GLAM? We'll miss that.

To figure out whether a probe is used, we "only" need to know:

* Name of probe (Firefox Telemetry only. Though if this becomes a general mechanism for detecting "this metric isn't being looked at and should probably be retired" for Glean that'd be wicked cool)
* Day (server time) it was accessed
* Count of accesses on that day (this one's kinda optional, but I want to be able to sum accesses over time)

I'd also like a pleasant way to query this (dump it into BQ?), but I'd settle for some magic incantations if that's what it takes. I can always pull it to iodide and make a UI there (I think. It's been a while.).

**Comment by robhudson** [comment]
You could do something like probe-search is doing here:
https://github.com/mozilla/probe-search/blob/main/probes/management/commands/import_telemetry.py#L96-L102

If a probe isn't in the resulting set then glam hasn't seen it in the last 3 versions.

**Comment by chutten** [comment]
That would certainly help find probes that are no longer being sent, thank you.

The use case I'm more interested in is a probe that is still sending data (of unknown quality) that no one ever looks at. Say [`GC_MAX_PAUSE_MS_2`](https://probes.telemetry.mozilla.org/?search=max_pause&view=detail&probeId=histogram%2FGC_MAX_PAUSE_MS_2) is sending millions and millions of samples, but is never queried, never put in a dashboard, never looked at through GLAM or the Measurement Dashboard. It'd be nice to know that so
1. Most immediately, we don't waste time migrating it
2. Perhaps in future we can automate the process of telling data owners about unused data that can be removed

**Comment by robhudson** [comment]
We do have Google Analytics enabled on GLAM. Perhaps that could be used. Alternatively we could investigate if we have server logs which, if including the URL being accessed, would include both the product and probe. If those 2 do not work we'd have to implement something to record this.

**Comment by chutten** [comment]
Would you happen to know who I'd ask to get access to either of those things, @robhudson ?

**Comment by chutten** [comment]
I have been given access, _and_ been pointed to [this lovely dashboard](https://datastudio.google.com/s/hR5Bu3Utcbc) and [this query that powers it](https://console.cloud.google.com/bigquery?sq=760000474358:aae4982f18024d7283990d5ac38ee663) which should give me the data that I need.

Thanks!
