### ISSUE TITLE
Add sample counts

### ISSUE THREAD

**Issue by robhudson** [mozilla/glam#1240]
On TMO's evolution view the bottom chart shows the sample counts. The same could be done for GLAM. 

An example of how sample counts are meaningful was reported in the glam channel on Slack:
> I'm looking at telemetry for minor GCs and this shows us how many were performed.  Changing the GC scheduling affects how many GCs are run as well as how long they individually take, and the overall impact depends on both.

**Comment by Iinh** [comment]
I'm still not sure where to display the sample count when the data becomes available? Should it be under client count?

![CleanShot 2021-10-21 at 15 35 27@2x](https://user-images.githubusercontent.com/28797553/138345244-5e653f1d-f9b7-489a-a172-f77a4b7a7f3b.png)

@ecsmyth what do you think?

**Comment by jonco3** [comment]
> I'm still not sure where to display the sample count when the data becomes available? 

The original idea for this was to display a graph of sample counts like the client volume graph.  For example, like it does on TMO:

https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=Median&cumulative=0&end_date=2021-10-25&include_spill=0&keys=!__none__!__none__&max_channel_version=nightly%252F95&measure=GC_MINOR_US&min_channel_version=nightly%252F94&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2021-10-04&trim=1&use_submission_date=0

**Comment by alekhyamoz** [comment]
GLAM vs TMO sample counts [research notes here](https://docs.google.com/document/d/1T-0yWj6vaiWTN3lPiX5VXGW-WNEK4rOkgaIx7sKN_Sw/edit#)

Pending on ETL front: 
1. Add scalars to the etl 
2. Optimize the sql (may be remove keys? / build id as date)

Backend: 
Pull csv data to postgres
