### ISSUE TITLE
When outlier is shown on graph, scale on graph makes it difficult to use rest of the data

### ISSUE THREAD

**Issue by mcomella** [mozilla/glam#1256]
In https://glam.telemetry.mozilla.org/fenix/probe/perf_startup_application_on_create/explore?ping_type=*&ref=2021031317&timeHorizon=WEEK, the 2021-03-07 build has a skewed data point that drastically changes the scale and makes the rest of the visualization harder to use:
![image](https://user-images.githubusercontent.com/759372/111393369-e0752000-8675-11eb-874d-082b1afccbdb.png)

Ideally, we can change the scale or omit outliers in order to change the scale to better understand the remainder of the data.

fwiw, this skewed data point was caused by another bug https://github.com/mozilla-mobile/fenix/issues/18092 but presumably this could happen with real world data too.

**Comment by Iinh** [comment]
closed via #1379.
