### ISSUE TITLE
Metrics measured in `glean_client_info` appear in search but do not have data available

### ISSUE THREAD

**Issue by mcomella** [mozilla/glam#1322]
I noticed the architecture probe from the glean_client_info ping (or section of pings?) has no data: https://glam.telemetry.mozilla.org/fenix/probe/architecture/explore?ping_type=*

It looks like we are unable to support this data type so it probably shouldn't appear in search at all. I determined this from this #glam conversation:

> 2h
> emtwo  I looked in the early glam tables for architecture being processed but I don't see it.... @amiyaguchi perhaps would be helpful to trace it back to the type of glean ping it's coming from? You might be more familiar than me on where to look
> 2h
> amiyaguchi  This is talking about the architecture field in the client_info section in particular -- we don't aggregate from anything outside of the metrics section of the ping
> 2h
> amiyaguchi  you can search for "client_id" too, but it won't have any meaningful data
> 2h
> emtwo  hm, we probably shouldn't be allowing that as an option to search for

**Comment by edugfilho** [comment]
If we remove unsupported probes from the search results it might also get confusing because users might think their input is wrong or it or the probe doesn't exist. At the same time, the error page contains a link to Glean dictionary, which is pretty informative. We decided to keep it as is.
