### ISSUE TITLE
GPU process data not displayed

### ISSUE THREAD

**Issue by Bas-moz** [mozilla/glam#1390]
For probes that are collected mainly through the GPU process (particularly on Windows), like KEYPRESS_PRESENT_LATENCY or COMPOSITE_TIME. We currently only allow viewing the Parent process data, which is very limiting and biases the values quite strongly. We should be able to also see the GPU process numbers.

For example, <1000 clients on windows: https://glam.telemetry.mozilla.org/firefox/probe/keypress_present_latency/explore?os=Windows&process=parent
Or for example: https://glam.telemetry.mozilla.org/firefox/probe/composite_time/explore?os=Windows&process=parent

And there's several others like this.

**Comment by emtwo** [comment]
The GPU processes seems to not be included in the ETL processing at all for histograms. Here are a couple of references where this is happening:

1) In the [ETL generation](https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_v1.sql.py#L428-L439) (this sections should probably be written more clearly too...), 

2) In the [airflow job](https://github.com/mozilla/telemetry-airflow/blob/main/dags/glam.py#L126-L150) only the parent and content processes are set

**Comment by robhudson** [comment]
Re-opening and will close after verifying airflow jobs produce the data we are looking for.

**Comment by robhudson** [comment]
GPU processes are now available. Since it's new there will not be much historical data since the ETL aggregates current version + 2 versions in history.
