### ISSUE TITLE
SQL generation does not work for keyed histograms

### ISSUE THREAD

**Issue by rtestard** [mozilla/glam#1485]
STR:
- Go to https://glam.telemetry.mozilla.org/firefox/probe/external_protocol_handler_dialog_context_scheme/explore?activeBuckets=%5B%22OTHER%22%2C%22ZOOM%22%2C%22TELEGRAM%22%2C%22spotify%22%2C%22MACAPPSTORE%22%2C%22APPLE%22%2C%22APPLE_FINDMY%22%2C%22APPLE_LIVESTREAM%22%2C%22APPLE_MUSIC%22%2C%22BING%22%5D&process=parent
- Hit "View SQL query" then "Telemetry SQL"
- Copy and paste code to redash
- Observe errors, all keyed histograms seem to have the same issue wherre the query expects unkeyed histograms

**Comment by rafrombrc** [comment]
Eric is going to do a bit of investigation on this to understand the use cases and we'll work on implementation pending those results.

**Comment by alekhyamoz** [comment]
Conversation related to keyed histograms redash query: https://mozilla.slack.com/archives/CB1EQ437S/p1643731039180779
chutten provided pointers on how to make the query work in redash 
here is a sample query that worked for the user: https://sql.telemetry.mozilla.org/queries/84037/source#208182
