### ISSUE TITLE
Allow searching for event metrics

### ISSUE THREAD

**Issue by Iinh** [mozilla/glam#1490]
Currently we don't visualize event metrics, and this causes confusion as users often ask in the GLAM slack channel when they can't search for an event. Since this is a commonly asked question, we should provide some documentations in the UI that we're not currently indexing events, and maybe provide guidance on how to answer their event-related question in redash or relevant tools.

**Comment by wlach** [comment]
We now have an "events count" explore in Looker, which might answer some of the questions people have been wanting to use GLAM to answer. When we've sorted out a good default explore for this type of information in the Glean Dictionary, we can probably link to something similar from GLAM.

For another, similar issue with the `string_list` metric type, see #1566

**Comment by wlach** [comment]
When https://github.com/mozilla/glean-dictionary/pull/902 lands, we'll be able to say why a given Glean metric doesn't appear in GLAM. We should be able to use that to show a more meaningful message (directing the user to Looker and/or the Glean Dictionary) for that metric. Aside from that, the only other thing we should do is update the API (for Fenix/Glean) to not exclude events:

https://github.com/mozilla/glam/blob/83b4a25b618a27f3bcca13df3bb304d07f33d9d4/src/state/api.js#L81

**Comment by wlach** [comment]
We discussed closing this at today's meeting, but instead lets morph it to implementing https://github.com/mozilla/glam/issues/1490#issuecomment-942632780 once #1658 lands.

**Comment by Iinh** [comment]
Closing this issue because we can now search for event metrics on dev. Regarding the specific error message, we have agreed in the last triage meeting to open a separate bug for each metric type.
