### ISSUE TITLE
Work w Glean team to generate a doc of what products should include to support GLAM

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/glam#1550]
To support GLAM Glean products should ideally associate dates w build ids, and they should ideally have a mechanism to map version release markers to dates. Note that these might not apply in all cases (do glean.js products _have_ major releases?) but we should have them when they do, and we should make sure product owners know to include them.

**Comment by alekhyamoz** [comment]
[Here](https://docs.google.com/document/d/1fxVblBLDlpN0rw792vBmZgSc2yc4zW26o9C5PyIfcdY/edit#) is the documentation prepared with inputs from the Glean team.

**Comment by alekhyamoz** [comment]
Added the note : https://github.com/mozilla/glean/pull/1950
