### ISSUE TITLE
ETL and import for Firefox Desktop on Glean (FOG) probes

### ISSUE THREAD

**Issue by robhudson** [mozilla/glam#1559]
Telemetry based firefox desktop and FoG will have separate ETL pipelines. Ideally we keep the data separate as far as we can into GLAM, which means separate metrics in probe-search and separate aggregation tables in GLAM.

We propose that it would be best to have a unified search experience rather than a separate top level product pull-down for both.

This issue is to research how we can search both probe-search tables and pass the relevant data to the metric that is chosen so it gets directed to the right data.

**Comment by rafrombrc** [comment]
ETL is done, we've now got GLAM data sets with the Firefox Desktop Glean probes in them, and files sitting in GCS ready to be picked up by the importer. Next step is importing these into CloudSQL.

**Comment by alekhyamoz** [comment]
ETL is done. Import being tracked in #1737
