### ISSUE TITLE
`string_list` metrics are not supported by GLAM

### ISSUE THREAD

**Issue by wlach** [mozilla/glam#1566]
Similar to events, `string_list` metrics are not supported by GLAM:

https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/metrics_mozilla_products

I'm not sure how important this actually is, but getting an issue on file.

According to @chutten: "The way we handled this for string_list-like things in the past was to have an open-ended aggregation. Every time we saw a new string value we started counting them"

**Comment by chutten** [comment]
This sort of aggregation is expensive and never-ending, which might not be philosophically (or monetarily) amenable to GLAM's architecture... but if it _is_, then counts of clients who ever sent the most popularly-seen N strings in a list would be nice.

**Comment by wlach** [comment]
FWIW here's a list of string_list metrics used in Fenix: https://dictionary.telemetry.mozilla.org/apps/fenix?page=1&search=string_list

**Comment by rafrombrc** [comment]
The "this probe type is not supported" page links to the glean dictionary for the probe in question, which seems like a good resolution.
