### ISSUE TITLE
Increase minimum client count filter for Fx release channels

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/glam#1575]
Currently we filter out builds if they have <100 clients, but for release channels this is much too low... a build isn't a "real" build that got out there unless it's got millions of clients. I propose we bump the desktop release channel minimum to 50K. And we should look at the typical client counts for Fx Android release channel and bump the number there as well.

**Comment by ecsmyth** [comment]
As a simple heuristic, I propose we use roughly 0.5% of WAU.

[Desktop](https://mozilla.cloud.looker.com/explore/kpi/firefox_desktop_usage_2021?qid=9nATCGAEBtHKWqkkT48vI9&origin_space=63&toggle=fil,vis)
* Release: 625,000
* Beta: 9,000
* Nightly: 375

[Android](https://mozilla.cloud.looker.com/explore/fenix/growth_accounting?qid=7WxGfgfPUtMqVKRrSOzTMi&origin_space=191&toggle=vis)
* Release: 90,000
* Beta: 2,000
* Nightly: 800
