### ISSUE TITLE
Can't hover over most recent points on graph

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/glam#1580]
e.g. with https://glam.telemetry.mozilla.org/firefox/probe/paint_build_displaylist_time/explore?ref=20210909212746 the data goes to around Sept 14/15 but I can only hover over Sept 11

**Comment by wlach** [comment]
It looks like there's an oversized svg around here:

![image](https://user-images.githubusercontent.com/20569/138948322-c2f62469-50eb-4383-991c-2fdb0f4228bc.png)

If I manually set the width to 145px (the size of the containing element), hovering works again.
