### ISSUE TITLE
Consider using Glean Dictionary to search and display data relevant to Glean probes (e.g. for Firefox for Android)

### ISSUE THREAD

**Issue by wlach** [mozilla/glam#1581]
I might turn this into a proposal but filing an issue just to get the ball rolling.

Right now we use/store the [probe search service](https://github.com/mozilla/probe-search) to store and retrieve metric data.
This made some sense at the time GLAM was been developed (which was before the Glean dictionary) but the Glean Dictionary provides a much more sophisticated metadata model which includes:

* (fenix only) Tags to aid with metric discovery and use (e.g. https://dictionary.telemetry.mozilla.org/apps/fenix?page=1&search=Search)
* Annotations and commentary indicated how a metric should be interpreted (https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/browser_search_in_content)
* Links out to Looker explores relevant to the metric (especially useful if the metric is not visible in GLAM e.g. #1490, #1566)

For metrics themselves, we can probably just request the static resources in the Glean Dictionary directly. E.g. https://dictionary.telemetry.mozilla.org/data/fenix/metrics/data_addons_installed_addons.json

To return a set of results in response to a search, I have an experimental version of the Glean Dictionary which allows full text searching over the set of indexed metrics here:

https://github.com/mozilla/glean-dictionary/pull/834

Preliminary testing indicates it returns approximately the same results as the probe search service:

https://deploy-preview-834--glean-dictionary-dev.netlify.app/.netlify/functions/search?search=addons
https://dev.probe-search.nonprod.dataops.mozgcp.net/glean?limit=30&select=name%2Cdescription%2Ctype%2Cinfo&type=neq.event&or=%28name.eq.addons%2Csearch.plfts%28simple%29.addons%2Cdescription.phfts%28english%29.addons%2Cname.ilike.*addons*%29&not.and=%28type.eq.scalar%2Cinfo-%3Ecalculated-%3Elatest_history-%3Edetails-%3E%3Ekind.eq.string%29&order=info-%3Ecalculated-%3E%3Eactive.desc&product=eq.fenix

**Comment by robhudson** [comment]
Would we change the flow so users start on Glean Dictionary with a link out to GLAM? Or vice versa? Or some other UI change I'm not clear on here?

**Comment by wlach** [comment]
> Would we change the flow so users start on Glean Dictionary with a link out to GLAM? Or vice versa? Or some other UI change I'm not clear on here?

I would keep the UI and flow more-or-less the same for now -- we can just add more metadata inside the GLAM pages for each metric. At some point we might want to consider unifying GLAM and the Glean Dictionary in some way, but that would require some thought and care.

**Comment by wlach** [comment]
Part of this was implemented in #1625, filed a new issue (#1678) for the rest of it.
