### ISSUE TITLE
Add Mozilla VPN

### ISSUE THREAD

**Issue by mdboom** [mozilla/glam#1603]
It would be great to add Mozilla VPN to the GLAM dashboard.  We expect correct Glean data to start flowing in around October 20, 2021 from the next VPN release.

**Comment by birdsarah** [comment]
The versioning for mozilla vpn is standard [semantic versioning](https://semver.org/), we're in v2.5 now (major "2", minor "5") and about to put out a patch release which will be v2.5.1

The next version, with upgraded glean, will be v2.6.

**Comment by mdboom** [comment]
Now that I understand this better, I think it's fine to deprioritize this work.  It looks like all of VPN's telemetry is in events.  GLAM doesn't yet support events, and even when it does, the expectation is that it will just be aggregate counts.  For event funnels, the better tool is Looker.

Let me know if you have any questions, @birdsarah.

**Comment by birdsarah** [comment]
How do we get default dashboards based on our defined metrics?

**Comment by mdboom** [comment]
@birdsarah: Some default dashboards for event funnels have now been set up in Looker: https://mozilla.cloud.looker.com/explore/mozilla_vpn/funnel_analysis?toggle=fil,vis,vse&qid=Id5RndasXDM4rVIE4TXk66
