### ISSUE TITLE
Add links out to Looker from GLAM metrics pages

### ISSUE THREAD

**Issue by wlach** [mozilla/glam#1610]
In many cases, a Looker explore for a metric may be a useful complement to the data GLAM displays. It is also useful in the case where GLAM doesn't support a metric type (e.g. events, see #1490). For these cases, we should streamline going to Looker for a metric.

The shortest path to implementing this probably runs through #1581

**Comment by rafrombrc** [comment]
This is only going to be possible for Glean metrics, we should show this as inactive for older Telemetry metrics (w tooltip as to why it's inactive).
