### ISSUE TITLE
allow version in API to be optional

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#163]
The GLAM frontend will likely not need to specify a version. As such, providing the version arguments requires a lot of hoop-jumping in the frontend that is inefficient – I have to find out what version is current, then subtract _k_ from that. It'd be nice if by default, if I don't provide `version`, I get all versions available, or perhaps the last _k_.

**Comment by robhudson** [comment]
Imagine a future where the imports have been running for awhile and the database has in it 10 versions of historical data. Would we want all that to be returned in the API by default? I imagine that might be a big JSON blob.

If we default to the last *k* versions, I imagine we'd want the API to support querying for other versions still if the user wants to see older data. Would that be a valid assumption?

**Comment by hamilton** [comment]
Yep, I think having the default be something sensible / recent seems like the right move, and using `version` for historical querying (which we'll probably need at some point).

I think we could have (for `build_id` as aggregation level) the last `B` days (maybe that translates to 2 or 3 versions worth of build ids total) and for version the last `V` versions (start w/ maybe 6 or so as max).
