### ISSUE TITLE
Add 0.1% and 1% percentile

### ISSUE THREAD

**Issue by Iinh** [mozilla/glam#1645]
The work required should be straight-forward, and similar to what we already did in #1576. 

It includes 2 parts:
- surface data in etl
- UI changes to the percentile buttons

**Comment by alekhyamoz** [comment]
Created a [PR](https://github.com/mozilla/bigquery-etl/pull/2723) waiting for a [CI failure PR]( https://github.com/mozilla/bigquery-etl/pull/2725/) to be merged

**Comment by Iinh** [comment]
Reassigning this to @edugfilho as this seems like a good front-end first bug.

Some prior art: 
- https://github.com/mozilla/glam/pull/1619
- https://github.com/mozilla/glam/pull/1649
