### ISSUE TITLE
Provide a more specific error message when we can't get information on a probe / metric

### ISSUE THREAD

**Issue by Iinh** [mozilla/glam#1658]
This is the current error page when a user visits a probe that has no data:

<img width="764" alt="CleanShot 2021-10-15 at 15 00 10@2x" src="https://user-images.githubusercontent.com/28797553/137539149-343e94af-36be-48aa-a254-d87a238b318e.png">

This error message is the same whether it's because of a UI bug, or because we don't have data for that probe yet, or we don't aggregate that metric type, etc.

We should make the error message more specific. For example, for metric types that we don't visualize, we can let users know that they can use Looker instead in the error message.

**Comment by alekhyamoz** [comment]
This ticket is too generic. Will open more specific issue 
Eg: #565
