### ISSUE TITLE
design the UX around persistent hover values

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#167]
A user will want to compare two builds or versions outside of the hovering context by "pinning" a hovered value for more static comparison to a reference. This will enable users to share the exact comparison to others via URL.

**Comment by chutten** [comment]
Use cases like "Wow, the 95 %ile really tanked since March's build <link>" or "Lemme just copy-paste that table of comparison values <mouses out of the plot>"

**Comment by edugfilho** [comment]
Being tracked in https://github.com/mozilla/glam/issues/2053
