### ISSUE TITLE
probes that are not probably active are marked as active

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#168]
It seems that there are cases where probes that are not likely to be active are marked as such. This is one such example:

![Screen Shot 2019-12-17 at 8 43 15 PM](https://user-images.githubusercontent.com/95735/71056374-ec3e0380-210d-11ea-8f8a-24ba73492e4c.png)

**Comment by rafrombrc** [comment]
Lots of work to handle issues w missing or bad data, this is mostly resolved.
