### ISSUE TITLE
move search out of client and into a probe search service

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#172]
When we started building GLAM, it was unclear what the server architecture would be. So we opted to do all the search client side, which is limited for the volume of probes we're indexing. Since we've moved to django, perhaps a postgres search API will be a huge improvement.

Ideally, however, we can solve this issue for a handful of data tools at once. The probe dictionary would benefit from this as well. The right solution might actually look more like a search API we can consume from both GLAM and the probe dictionary.

**Comment by hamilton** [comment]
Can we get a status report on this? @robotblake @robhudson ~ would be great if we could have an ETA while we prepare Fenix probes

**Comment by robotblake** [comment]
I'm working on getting the `dev` version of this up this afternoon.

**Comment by robotblake** [comment]
This took longer than expected due to some unforeseen permission and infra related issues, those have now been resolved and I'm pushing on this again for today.

**Comment by hamilton** [comment]
@robotblake sounds good, thanks for the update!
