### ISSUE TITLE
provide the raw probeId as part of the probes API payload

### ISSUE THREAD

**Issue by spasovski** [mozilla/glam#173]
It might even be good to leave the `scalar/` `histogram/` prefix for better mapping to the probeIDs in probe dictionary. This will be used for generating a link to open the probe in PD.

**Comment by robhudson** [comment]
See: https://github.com/mozilla/glam/pull/174

Will require ops when deployed.

**Comment by robhudson** [comment]
This has been completed and will be deployed along with the import deployment.
