### ISSUE TITLE
Import FOG probe data into GLAM

### ISSUE THREAD

**Issue by alekhyamoz** [mozilla/glam#1737]
As the next step to get FOG into GLAM UI, we need to make the necessary Django script changes to import FOG CSV data (residing in GCS bucket) into Postgres table

**Comment by alekhyamoz** [comment]
Created a [PR](https://github.com/mozilla/glam/pull/1771) for django changes for FOG

**Comment by alekhyamoz** [comment]
The implementation has been deployed to the dev environment. 
Created a couple of tickets requesting DSREs support for testing in dev
https://mozilla-hub.atlassian.net/browse/DSRE-429
https://mozilla-hub.atlassian.net/browse/DSRE-430

**Comment by Iinh** [comment]
Some notes on the front-end work required for FOG:

- First, we need to consolidate legacy telemetry and FOG search API so we only need to hit 1 API for Firefox dropdown search (this work needs to be done in the Glean Dictionary)
 - Then, use this new API for desktop search
- UI-wise, add visual treatment to the search results so users can differentiate between FOG and legacy probes

**Comment by alekhyamoz** [comment]
The front-end work is being tracked in #1809
