### ISSUE TITLE
Should use Glean Dictionary's "official" search API

### ISSUE THREAD

**Issue by wlach** [mozilla/glam#1761]
In #1736 we swapped in the Glean Dictionary as the source of probe/metric metadata. However, it's using the weird `.netlify` API endpoint. Instead we should use the new API search endpoints landed in https://github.com/mozilla/glean-dictionary/pull/1028.

Should just require a change small here to update the path:

https://github.com/mozilla/glam/blob/a075a955ab8626565bc1fa28e919a92a351edecb/src/state/api.js#L61

**Comment by Iinh** [comment]
TODO: We need to publish a new Glean Dictionary release to be able to use the production search API, which should be done after [the tag issue](https://matrix.to/#/!bYOjfdNDYkOXZgaNEI:mozilla.org/$eBSOpiP32WsuNa7Iwg5qjAOVgE1nUO9Fbjy0ho7Mo8A?via=mozilla.org&via=matrix.org&via=ungleich.ch) is fixed.
