### ISSUE TITLE
GLAM's visualization of video_dropped_frames_proportion is much less useful than t.m.o's

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/glam#1807]
Compare:
https://glam.telemetry.mozilla.org/firefox/probe/video_dropped_frames_proportion/explore?timeHorizon=QUARTER

vs

https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=Median!Mean!5th%2520percentile!25th%2520percentile!75th%2520percentile&cumulative=0&end_date=null&include_spill=0&keys=&max_channel_version=nightly%252F98&measure=VIDEO_DROPPED_FRAMES_PROPORTION&min_channel_version=nightly%252F95&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=null&trim=1&use_submission_date=0

In GLAM all of the percentile's are 0 except for 95%

**Comment by Iinh** [comment]
We're trying to figure out the most optimal way to show non-normalized aggregations in GLAM, in addition to the current data that's aggregated by client id. Updates on this issue will be posted in #1929.

**Comment by edugfilho** [comment]
The solution to this will be implemented in https://github.com/mozilla/glam/issues/2085.
@jrmuizel please subscribe to the issue above to continue to receive updates on this issue!
Closing this ticket as a duplicate
