### ISSUE TITLE
 Front-end (UI) work required for FOG

### ISSUE THREAD

**Issue by alekhyamoz** [mozilla/glam#1809]
The next step after importing FOG data is to make the data visible via GLAM UI

**Comment by Iinh** [comment]
Some notes on the front-end work required for FOG:

- First, we need to consolidate legacy telemetry and FOG search API so we only need to hit 1 API for Firefox dropdown search (this work needs to be done in the Glean Dictionary)
- Then, use this new API for desktop search
- UI-wise, add visual treatment to the search results so users can differentiate between FOG and legacy probes
