### ISSUE TITLE
Add support "Distribution view" to "View SQL Query"

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/glam#1837]
Currently "View SQL Query" has SQL that generates a chart something like the "Evolution" tab of telemetry.mozilla.org. It would be valuable to have the SQL for the "Distribution" tab.

**Comment by alekhyamoz** [comment]
Hi @jrmuizel, as communicated with you, while this issue, to add the Distribution view to GLAM front-end UI, is being prioritized as part of our M6 milestone. 
Meanwhile, I have developed [this redash query ](https://sql.telemetry.mozilla.org/queries/84626) that might be helpful.  It represents the GLAM's violin chart which is the TMO's Distribution view flipped 90 degrees.
