### ISSUE TITLE
Remove probes throwing "network error" from GLAM ETL

### ISSUE THREAD

**Issue by alekhyamoz** [mozilla/glam#1865]
This issue is a development effort related to research done in #1841. 
There were 2 options to go about reducing the ETL and operational efforts pertaining to the "network error" probes 
1. Quick and dirty, remove the probes from the ETL calculations
2. Long-term strategy, build an api that will be leveraged in the ETL to pick up the hot cached probe. 

It was decided to go with option 1, as this effort will help us understand the gains and pain points of our long-term strategy involved with optimizing GLAM

**Comment by alekhyamoz** [comment]
Created ticket #1894 to track the work required for backend changes.

**Comment by edugfilho** [comment]
Closing this since all sub-issues were also closed
