### ISSUE TITLE
https://glam.telemetry.mozilla.org/firefox/probe/video_dropped_frames_proportion_exponential/explore? doesn't load

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/glam#1875]
I get "Oh no! The server encountered an error.
If you think this is a bug, report this on the [#glam](https://mozilla.slack.com/archives/CB1EQ437S) channel on Mozilla's Slack instance or in the [GLAM github repository](https://github.com/mozilla/glam/issues/new)."

**Comment by whd** [comment]
See https://mozilla-hub.atlassian.net/browse/DSRE-591 for status

**Comment by whd** [comment]
Closing in favor of upstream issue, which seems to be resolved.
