### ISSUE TITLE
Update Dockerflow Application Endpoints for Glam App

### ISSUE THREAD

**Issue by cmharlow** [mozilla/glam#1887]
According to the [Dockerflow specification](https://github.com/mozilla-services/Dockerflow) (a SRE practice that Glam somewhat follows currently), the Glam application should support 3 endpoints:

1. https://glam.telemetry.mozilla.org/__version__ (this currently fails missing a file)
2. https://glam.telemetry.mozilla.org/__heartbeat__ (this works but the check itself shows warning - we should understand why)
3. https://glam.telemetry.mozilla.org/__lbheartbeat__ (this doesn't work currently)

If SRE gets to this first, we'll do it - but noting this here for the Glam Dev team to call out the version endpoint in particular. This should be a pretty straight forward addition to the CI & Dockerfile (see the example in the linked repo above). 

Linked SRE ticket: https://mozilla-hub.atlassian.net/browse/DSRE-621

**Comment by alekhyamoz** [comment]
SRE to partner with dev team
