### ISSUE TITLE
Getting 404 data not found error for all Fenix metrics on stage and prod

### ISSUE THREAD

**Issue by Iinh** [mozilla/glam#1893]
Locally and on dev everything is working fine. Stage and prod are getting the below error for all Fenix probes:

[dev](https://dev.glam.nonprod.dataops.mozgcp.net/fenix/probe/addons_has_enabled_addons/explore?activeBuckets=%5B%22never%22%2C%22always%22%2C%22sometimes%22%5D&aggType=avg&currentPage=1)

<img width="1029" alt="CleanShot 2022-03-23 at 15 59 26@2x" src="https://user-images.githubusercontent.com/28797553/159785389-a524763f-7fb8-4c58-b237-73480d0f59ea.png">

[stage](https://stage.glam.nonprod.dataops.mozgcp.net/fenix/probe/addons_has_enabled_addons/explore?aggType=avg&currentPage=1) and [prod](https://glam.telemetry.mozilla.org/fenix/probe/addons_has_enabled_addons/explore?aggType=avg&currentPage=1&ping_type=*)

<img width="1354" alt="CleanShot 2022-03-23 at 15 47 30@2x" src="https://user-images.githubusercontent.com/28797553/159783444-6e5f891a-de4f-40de-98cc-f14101984f65.png">

Not sure if this is helpful, but for eg the probe above, this is the query sent to the database:

```
SELECT "view_glam_fenix_aggregation"."id", "view_glam_fenix_aggregation"."app_id", "view_glam_fenix_aggregation"."channel", "view_glam_fenix_aggregation"."version", "view_glam_fenix_aggregation"."ping_type", "view_glam_fenix_aggregation"."os", "view_glam_fenix_aggregation"."build_id", "view_glam_fenix_aggregation"."build_date", "view_glam_fenix_aggregation"."metric", "view_glam_fenix_aggregation"."metric_type", "view_glam_fenix_aggregation"."metric_key", "view_glam_fenix_aggregation"."client_agg_type", "view_glam_fenix_aggregation"."total_users", "view_glam_fenix_aggregation"."histogram", "view_glam_fenix_aggregation"."percentiles", "view_glam_fenix_aggregation"."total_sample" FROM "view_glam_fenix_aggregation" WHERE ("view_glam_fenix_aggregation"."app_id" = 'nightly' AND "view_glam_fenix_aggregation"."metric" = 'addons_has_enabled_addons' AND "view_glam_fenix_aggregation"."ping_type" = '*' AND "view_glam_fenix_aggregation"."version" IN (100, 99, 98) AND "view_glam_fenix_aggregation"."os" = 'Android' AND NOT ("view_glam_fenix_aggregation"."build_id" = '*'));
```

The dev team currently doesn't have permission to view `view_glam_fenix_aggregation` table to verify if there's data.

**Comment by Iinh** [comment]
Please disregard the "expired" expiry status warning; `addons.has_enabled_addons` is still active. This is a known bug and will be fixed after https://github.com/mozilla/glam/pull/1892 is merged.

**Comment by cmharlow** [comment]
so a few things:
1. this is duplicated in stage, and @Iinh yall all should have access to stage db (at least the gcp resources around it) right now for debugging.
2. i'm working in the private SRE ticket now to pin down the 404. It doesn't look to be a database issue. the app user can access & the data is present for the query you provided.

**Comment by cmharlow** [comment]
Temporary solution in place. Long term solution detailed in SRE ticket.

**Comment by alekhyamoz** [comment]
We have noticed that the bad app versions have been making it to the GLAM backend via the ETL. 
I have put a quick fix in place [PR](https://github.com/mozilla/bigquery-etl/pull/2820)
The long term solution includes : 
1. Identify the records in BQ that were the root cause of these bad versions and come up with a permanent fix
2. rewrite that view versions lookup to ignore the inaccurate versions. [PR by Christina](https://github.com/mozilla/glam/pull/1895) to show one possible approach that would fix this in the app
