### ISSUE TITLE
Create component for collecting instrumentation data

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glam#1912]
Sub-issue of #1847.

The scope of this issue is to quickly enable Glam to collect metrics on probe searching to help reduce GLAM ETL work.

Enable GLAM App back-end code to collect probe usage data from user requests and save it to a table.

- [x] Save basic probe searching info to a table
- [x] Create models (DB tables)
- [x] Create a component for data collection (back-end)
- [x] Create a service to save and serve collected metrics (endpoint for serving)

**Comment by edugfilho** [comment]
I will test this on dev and check if metrics are properly collected and served there. 

When this gets deployed to prod we will start collecting metrics there and it will be useful to accumulate prod data even though we can't use it to reduce ETL effort yet, because once we can we'll have more data to work with (see comment on #1913 )

**Comment by edugfilho** [comment]
@Iinh this is tested in Dev and looking good to go to staging

**Comment by Iinh** [comment]
Nice! Thanks for the update @edugfilho
