### ISSUE TITLE
only update querystring on "meaningful" state changes

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#192]
At the moment, the querystring pretty much updates whenever anything in the store changes. There are a number of state changes that are often done on the road to a more finished state before a user has a chance to interact with the frontend – for instance, when a user selects a probe that has proportions (like `histogram-enumerated`) we have to find what keys to show by default (sometimes a subset of all the possible keys). This involves more than one state change. 

We need an easy way of saying "don't update the query string here but do update it there". The most obvious way is an optional third boolean argument in `store.setField` that allows you to set the query string or not (default to `true`).

This will make the back button only go through explicit userland states.

Down the road, when we roll out an undo / redo function, we will probably want something like this as well.

**Comment by openjck** [comment]
Hamilton and I have been talking about this on Slack. We decided to close it as *wontfix* for now.
