### ISSUE TITLE
Formulate a strategy for non-normalized distribution

### ISSUE THREAD

**Issue by Iinh** [mozilla/glam#1929]
In order to decommission TMO successfully, we need to make sure that all TMO needs are covered by GLAM. Since TMO does non-normalized aggregations, and GLAM does not, and from recent discussions, we know that there is a clear need for the non-normalized distribution, we need to figure out how we can make this happen in GLAM.

Some suggestions from @rafrombrc:
- let the etl double calculate? this is a lot of work for an already resource-intensive process
- let the api/backend code handle the non-normalized aggregations, which would reduce the workload for etl, but is it feasible?

**Comment by edugfilho** [comment]
The strategy is to finish the hotlist-driven ETL and introduce the non-normalized calculations to the ETL, then finally add a toggle (similar to the sample count) to the graph to switch between the normalized and non-normalized version.

Our target is to get this done and have TMO turned off by end of H1 '23 latest (end of April)
