### ISSUE TITLE
No data shows up for MEDIA_DECODER_BACKEND_USED

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/glam#1932]
Compare:
https://glam.telemetry.mozilla.org/firefox/probe/media_decoder_backend_used/explore?currentPage=1

vs
https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2022-03-08&include_spill=0&keys=__none__!__none__!__none__&max_channel_version=nightly%252F99&measure=MEDIA_DECODER_BACKEND_USED&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_by_value=0&sort_keys=submissions&start_date=2022-02-07&table=0&trim=1&use_submission_date=0

**Comment by Iinh** [comment]
Hi @jrmuizel, we do have data for this probe with the GPU process specifically.

![CleanShot 2022-04-20 at 12 56 28@2x](https://user-images.githubusercontent.com/28797553/164283510-75f85a7f-0bac-4db1-be40-8beb40573563.png)


https://glam.telemetry.mozilla.org/firefox/probe/media_decoder_backend_used/explore?activeBuckets=%5B%222%22%2C%220%22%2C%221%22%2C%223%22%2C%224%22%2C%225%22%2C%226%22%2C%227%22%2C%228%22%2C%229%22%5D&currentPage=1&process=gpu
