### ISSUE TITLE
Glam ETL probe name snake_casing is incompatible with Glam's for scalar probes

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glam#1956]
spinoff of [glam#1954](https://github.com/mozilla/glam/issues/1954)

Glam ETL [snake_cases scalar probe names](https://github.com/mozilla/bigquery-etl/blob/d79e41a17afc0d3c8958b7645c4c70b2a57521c7/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1.sql.py#L452) in a way that [even camelCase names are snake_cased](https://github.com/mozilla/bigquery-etl/blob/812ceb540ebb1f3f542304cf6c5df43a2be4a3dc/bigquery_etl/util/common.py#L27), while GLAM only takes already lowercased names from dtmo and [replaces their dots with underscores](https://github.com/mozilla/glam/blob/28e8fa00a302d4ec92ece77a51c9206265440ec7/src/components/search/SearchResults.svelte#L291). 

Example:
Probe original name: `privacy.restrict3rdpartystorage.rollout.enabledByDefault`
Glam looks for (and doesn't find): `privacy_dfpi_rollout_enabledbydefault`
Glam DB has data for:   `privacy_dfpi_rollout_enabled_by_default`

The result of this is that Glam is unable to find any scalar metric with a camelCased word in the name from its db.
Glam needs to apply snake_casing to probe names the same way Glam ETL does. 

Note that it is probably impractical to change Glam ETL instead, to adapt to Glam's snake_casing. Because the ETL does what it does to comply with the schema of _moz-fx-data-shared-prod.telemetry_stable.main_v4_ (see [this comment](https://github.com/mozilla/glam/issues/1954#issuecomment-1113681195))

Below is a list of scalar probes with camelCase in their names pulled from [probeInfo](https://probeinfo.telemetry.mozilla.org/firefox/all/main/all_probes) with some regex. I tested a small sample from this list and could confirm the issue with all the tested probes, meaning the probe's data exist in glam's db, in a different format, and glam can't find it.

```
blocklist.lastModified_rs_addons
blocklist.lastModified_rs_addons_mlbf
blocklist.lastModified_rs_plugins
blocklist.lastModified_xml
blocklist.useXML
browser.ui.interaction.preferences_paneContainers
browser.ui.interaction.preferences_paneExperimental
browser.ui.interaction.preferences_paneGeneral
browser.ui.interaction.preferences_paneHome
browser.ui.interaction.preferences_paneMoreFromMozilla
browser.ui.interaction.preferences_panePrivacy
browser.ui.interaction.preferences_paneSearch
browser.ui.interaction.preferences_paneSearchResults
browser.ui.interaction.preferences_paneSync
browser.ui.interaction.preferences_paneUnknown
datasanitization.network_cookie_lifetimePolicy
datasanitization.privacy_clearOnShutdown_cache
datasanitization.privacy_clearOnShutdown_cookies
datasanitization.privacy_clearOnShutdown_downloads
datasanitization.privacy_clearOnShutdown_formdata
datasanitization.privacy_clearOnShutdown_history
datasanitization.privacy_clearOnShutdown_offlineApps
datasanitization.privacy_clearOnShutdown_openWindows
datasanitization.privacy_clearOnShutdown_sessions
datasanitization.privacy_clearOnShutdown_siteSettings
datasanitization.privacy_sanitize_sanitizeOnShutdown
devtools.grid.showGridAreasOverlay.checked
devtools.grid.showGridLineNumbers.checked
devtools.grid.showInfiniteLines.checked
dom.contentprocess.buildID_mismatch
dom.contentprocess.buildID_mismatch_false_positive
firstStartup.elapsed
firstStartup.statusCode
formautofill.creditCards.autofill_profiles_count
formautofill.creditCards.detected_sections_count
formautofill.creditCards.fill_type_autofill
formautofill.creditCards.fill_type_autofill_modified
formautofill.creditCards.fill_type_manual
formautofill.creditCards.submitted_sections_count
fxrPC.isFirstRun
privacy.dfpi_rollout_enabledByDefault
```

**Comment by edugfilho** [comment]
Trying to fix this today I realized this is beyond Glam, because the probe name returned by Glean Dictionary is already completely lower-cased, so things like _"camelCasedProbeName"_ come back as _"camelcasedprobename"_ (while in  Glam DB such name would be _"camel_cased_probe_name"_) so we can't properly snake_case the name anymore.

I don't have a lot of knowledge on Glean Dictionary, but looking at the code there I suspect we can have that service return the probe name snake_cased properly or have it also contain the probe _id_, which is - I think - the probe name in its canonical form (_"camelCasedProbeName"_).

@Iinh you seem to know Glean Dictionary, can you please lend a hand?

**Comment by Iinh** [comment]
Great investigation work @edugfilho! I'm going to work on adding the probe id to the Glean Dictionary API search results.

**Comment by edugfilho** [comment]
awesome. Thank you! 
I'll have the changes to use the id ready in Glam so when it's available I'll test and open a PR

**Comment by Iinh** [comment]
Glean Dictionary prod API should return legacy probes with id now. For example: https://dictionary.telemetry.mozilla.org/api/v1/metrics_search_fog_and_legacy?search=privacy

**Comment by edugfilho** [comment]
awesome! thanks @Iinh
