### ISSUE TITLE
long string key values cause unfortunate overflows

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#201]
![Kapture 2020-01-17 at 17 08 20](https://user-images.githubusercontent.com/95735/72655825-0b69c400-394c-11ea-83f4-ac01120f05ae.gif)

**Comment by robhudson** [comment]
And there are much longer ones than that. My import is truncating them to 200 characters, which may or may not be a great idea? 

@emtwo What's your thought about truncating these on import? Many keys come from the client and are filled with junk and is the source of the character encoding problem we ran in to.
