### ISSUE TITLE
Investigate which use counters are inactive and why, and serve them on Glam 

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glam#2029]
Glam is currently not serving some use counters (see screenshot below) due to them being inactive.
A recent request on the Glam Slack channel brought to our attention that having them on Glam would be extremely useful for comparing them with other counters.

<img width="577" alt="Screen Shot 2022-06-23 at 2 33 32 PM" src="https://user-images.githubusercontent.com/5804462/175370561-340d7297-4108-43ac-9b0e-1faaf5df322b.png">

This aims to find and implement a satisfying solution so we can fulfill the need above

**Comment by edugfilho** [comment]
Contribution by @Iinh:
* Glean Dictionary marks a probe as inactive when it doesn't see it recorded in the [Client Probe Processes public dataset](https://github.com/mozilla/glean-dictionary/blob/b6c1fccb8c108576eae1b45a0dd8e84e964ce8d7/etl/firefox_legacy_etl.py#L12-L15)
* Traversing the dependency tree of the [source table](http://-%20https//mozilla.github.io/bigquery-etl/mozdata/telemetry/#client_probe_processes) of that public dataset, it points to these 4 GLAM etl tables
<img width="980" alt="Screen Shot 2022-06-23 at 2 40 09 PM" src="https://user-images.githubusercontent.com/5804462/175373122-371e7281-b70e-4101-9924-580b2a2bd49f.png">

* Code reference: https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/telemetry/client_probe_counts_v1/view.sql

* so it looks like if GLAM is not building a probe, that probe won't be marked as active in the Glean Dictionary. I think the solution to labeling this probe as active in the dictionary is just to add it to the list of metrics we're aggregating

* References:
[Client Probe Processes metadata](https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/telemetry_derived/client_probe_processes_v1/metadata.yaml)
https://github.com/mozilla/glean-dictionary/blob/b6c1fccb8c108576eae1b45a0dd8e84e964ce8d7/etl/firefox_legacy_etl.py#L53
https://mozilla.github.io/bigquery-etl/mozdata/telemetry/#client_probe_processes
https://mozilla.github.io/bigquery-etl/mozdata/telemetry/#client_probe_counts_v1

**Comment by Iinh** [comment]
Digging through old resources I found this diagram for legacy etl (this one is from a [data club talk](https://docs.google.com/presentation/d/1wl9TOLm4AAWYk1n7-YBeiWmXwjGv1diKxxln5f13uho/edit#slide=id.ga92241ec0c_1_1471) that @emtwo gave a while ago):

<img width="1265" alt="CleanShot 2022-06-29 at 13 24 48@2x" src="https://user-images.githubusercontent.com/28797553/176498536-5eee4e08-87ce-4cd1-b9f9-416ca2c29852.png">

After checking the parent table `clients_daily_histogram_aggregates_parent_v1`, looks like [this is the list of all the metrics](https://github.com/mozilla/bigquery-etl/blob/814ccc512f94c6e5e3092a743dc028840e6f3923/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_parent_v1/query.sql#L73) we're aggregating. Doing a quick search I don't see `use_counter2_deprecated_mathml_deprecatedstixgeneraloperatorstretching_document` -- the probe the user asked for -- in here. At this point seems like the solution is to manually add it to the list.

However I'm still investigating why this probe wasn't picked up, because I do see other `use_counter2` probes in there.

**Comment by edugfilho** [comment]
Seems like that list is build dynamically and it looks like [this part](https://github.com/mozilla/bigquery-etl/blob/d9e0c2abaab6feb13b7bde47a9493fa91013d880/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_v1.sql.py#L467) is responsible for bringing all the probes that are going to make that list. 
What the code above does is include the probe in the list if the probe is both in the response of [PROBE_INFO_SERVICE](https://probeinfo.telemetry.mozilla.org/firefox/all/main/all_probes) and in `telemetry_stable.main_v4.payload.histograms`.

With that in mind I went to check `telemetry_stable.main_v4.payload.histograms` and found `payload.histograms.use_counter2_deprecated_math_ml_deprecated_stixgeneral_operator_stretching_document` there, despite its value being `null` most of the time.


<img width="1942" alt="Screen Shot 2022-06-30 at 2 08 54 PM" src="https://user-images.githubusercontent.com/5804462/176747715-4c6c43dd-8bf7-4683-8769-51f0b6b5ae36.png">

**Comment by edugfilho** [comment]
Seems like the reason Glam does not process the probe  `use_counter2_deprecated_math_ml_deprecated_stixgeneral_operator_stretching_document` is because the probe data does not have enough client submissions, which would make the aggregation done on the data show potentially unreliable information:

![](https://user-images.githubusercontent.com/28797553/176498536-5eee4e08-87ce-4cd1-b9f9-416ca2c29852.png)
According to Desktop Glam, [clients_histogram_bucket_counts](https://github.com/mozilla/bigquery-etl/blob/d9e0c2abaab6feb13b7bde47a9493fa91013d880/sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_bucket_counts_v1/query.sql#L69) query filters out aggregations with less than an amount of individual client submissions (the actual number depends on the channel and for `nightly` it is `375`). 

With that info I went to check how many distinct clients submitted the probe in question. For that I used [this query](https://sql.telemetry.mozilla.org/queries/86750/source) that was based on [clients_histogram_bucket_counts](https://github.com/mozilla/bigquery-etl/blob/d9e0c2abaab6feb13b7bde47a9493fa91013d880/sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_bucket_counts_v1/query.sql#L1). The query scans `use_counter2_deprecated_math_ml_deprecated_stixgeneral_operator_stretching_document` on `moz-fx-data-shared-prod.telemetry_derived.clients_histogram_aggregates_v1` from Jan 1 2021 to Jul 5 2022 and does not return any rows.

Glam does not process/shows info for probes with fewer client submissions than a predetermined number per channel because the data displayed on Glam is aggregated and, as said in the first paragraph, the aggregation done on the data might result in inaccurate information if there aren't enough samples.

**Comment by edugfilho** [comment]
closing the issue with the end of this investigation
