### ISSUE TITLE
Allow determining precise bucket values in the compare panel

### ISSUE THREAD

**Issue by moztcampbell** [mozilla/glam#2031]
Example: https://glam.telemetry.mozilla.org/firefox/probe/gc_budget_overrun/explore?currentPage=1&ref=20220410213958&timeHorizon=ALL&visiblePercentiles=%5B50%5D

There is an interesting cliff on the histograms visible in the compare view. I'd like to find out the bucket ranges to understand where the cutoff between the two behaviours might be, but I'm not sure in the current UI.

In this case, knowing the bucket value of the discontinuity might hint what some unexpected behaviour in how GC time-slice budgets are computed.

**Comment by moztcampbell** [comment]
The work around (from Rob Miller) was to use the compare-in-STMO option to get an alternate way to look see buckets. This solved my immediate question.

**Comment by edugfilho** [comment]
https://github.com/mozilla/glam/pull/2488 fixes this
