### ISSUE TITLE
Violin plot is too small

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glam#2055]
Suggested by Bas, during interview
We have to discuss a solution for this one; so far we learned the violin plot is not big enough for some analysis, and for the same reason we can't add some functionalities to it, such as displaying the bucket over which the user is currently hovering the mouse.
 - We can't simply make it bigger because that would impact the page UI as a whole.
 - @rafrombrc suggested a modal for a different plot -  a **line chart where users could compare histograms for two different build ids** - as a way to have a bigger and more informative chart, in which we could embed more functionalities
 
Example for a line chart showing the same info as the violin plot can be found in [this STMO comparison page](https://sql.telemetry.mozilla.org/dashboard/test_38?p_Build%201=20220617093907&p_Build%202=20220602214637&p_Days%20to%20Query=7&p_OS%20Filter=%20&p_Probe=payload.processes.content.histograms.gc_mmu_50&p_Start%20Date=2022-06-17&p_Start%20Date%202=2022-06-02&p_Table=telemetry.main_nightly&p_channel=nightly) under Histogram Comparison (bottom left)

**Comment by Iinh** [comment]
This is related to #2031.

**Comment by edugfilho** [comment]
https://github.com/mozilla/glam/pull/2488 fixes this
