### ISSUE TITLE
verify in the updated dataset that histogram-enumerated is coded in the metadata is not coded as histogram-linear

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#206]
One complex bug in the demo data that we should be able to untangle with the updated set is that enumerated histograms are coded as linear histograms in the data. These tend to be pretty radically different and should be treated differently in the display, so we currently rely on the probe info service to figure out if a probe is actually a linear histogram. I believe this bug was fixed upstream. Once we are able to test locally, we should verify this.

**Comment by hamilton** [comment]
As of this comment, there is still an outstanding issue on the ETL side filed here: https://github.com/mozilla/glam/issues/244

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?
