### ISSUE TITLE
Toggle visualize non-normalized aggregations

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glam#2085]
Once [non-normalized aggregations](https://github.com/mozilla/bigquery-etl/issues/3139) are available we want to have Glam display them in a toggle fashion, such as the _view sample count_ option.

* Is blocked by [bigquery-etl#3139](https://github.com/mozilla/bigquery-etl/issues/3139)
* Blocks #1126 and #1807

**Comment by Iinh** [comment]
In addition to adding this toggle, we should consider making the non-normalized view the default, at least for nightly. See Bas's comment:

> But yes, for nightly I think non-normalized should be the default, in particular because something like 30% of nightly client run only for a couple of minutes per build. Meaning any per build work disproportionately skews measurements when normalizing per client. (For example a significant portion only produce 150 frames per build, all frames soon after an update which means we end up compiling shaders there, making the normalized histograms very skewed. We also see odd outliers in networking in the normalized data).

**Comment by Iinh** [comment]
Another thing we need to make available in the UI as part of this work is link to docs explaining the difference between the two types of aggregation.

**Comment by edugfilho** [comment]
Done in https://github.com/mozilla/glam/pull/2480
