### ISSUE TITLE
Probe browser_ui_interaction_content_context (release) causing Out of Memory app errors

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glam#2110]
Greg Tatum (@gregtatum) let us know of that in the Glam slack channel.

We noticed that the probe in question has a very high number of indexes, which is probably what's causing the errors.

**Comment by gregtatum** [comment]
Part of the problem is that the keys are effectively unbounded, as extensions can add arbitrary items to the context menu, and this probe counts how often a context menu item is clicked. The top 30-50 keys are the most relevant here, but then there is a long tail of random extension items.

**Comment by edugfilho** [comment]
Many thanks. We will tackle the issue with probes having too many keys by picking the top 50 keys in [this ticket](https://github.com/mozilla/glam/issues/2118)
