### ISSUE TITLE
GLAM export to JSON doesn't work

### ISSUE THREAD

**Issue by valenting** [mozilla/glam#2122]
**Describe the bug**
Nothing happens when I click on "Export to JSON".

**To Reproduce**
Load https://glam.telemetry.mozilla.org/firefox/probe/dns_trr_lookup_time3/explore?activeBuckets=%5B%22Fine%22%2C%22Timeout%22%2C%22Bad%22%5D&channel=release&currentPage=1&process=parent&timeHorizon=QUARTER or any other probe.
Click "Export to JSON"
Nothing happens. No errors in console.

**Expected behavior**
A json export of the data should be opened or downloaded.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 106.0a1 (2022-09-04) 
 - 
**Additional context**
Seems to work in Chrome.

**Comment by akkomar** [comment]
Might be a Nightly issue - export works for me in Firefox 103.0.2

**Comment by valenting** [comment]
Yes, this seems to be a recent regression.
I filed a bug for it [Bug 1789361 - Glam can't export to JSON after bug 1771423](https://bugzilla.mozilla.org/show_bug.cgi?id=1789361)

**Comment by edugfilho** [comment]
Ok :) I'll close this as a non-issue
