### ISSUE TITLE
come up w/ a way to handle large amounts of categories

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#216]
There are some enumerated probes with a _ton_ of entries, most of which are zero. It would be great if we hid the long tail of nothing behind a "more..." button. This could be 100% local state.

![Screen Shot 2020-01-23 at 7 31 14 AM](https://user-images.githubusercontent.com/95735/72998259-68cd9d00-3db2-11ea-970d-7e210478f216.png)

**Comment by hamilton** [comment]
I believe the solution to this is to move to a multi-selectable option menu. I have a sketch of one from the incline dashboard that should make it back into `graph-paper`. As such, I'll assign this to myself.

**Comment by openjck** [comment]
I talked with Hamilton and we agreed that I would take this on. As Hamilton said, there's a sketch of a component in moment-x-dashboard that will help. It also has a corresponding story. Hamilton suggested I manually copy it to *src/components/controls* for now; not *udgl*.
