### ISSUE TITLE
Events are not supported but GLAM doesn't explicitly informs it

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glam#2199]
GLAM currently does not support event metrics. However they're still searchable, and once an event is selected a `404: No data found for the selected dimensions.` message is displayed, which might lead users to think GLAM supports events but the selected one doesn't have data, which is not true.

Being explicit about not supporting event metrics would avoid confusion.
Suggestions by @chutten:
1) Hide events from the search dropdown 
2) Provide a custom "metrics of this type aren't yet supported" message

**Comment by Iinh** [comment]
> 1. Hide events from the search dropdown
> 2. Provide a custom "metrics of this type aren't yet supported" message

We should go with option 2 as this is how we're currently showing for the other metric types that we don't support, such as boolean scalar. See: https://glam.telemetry.mozilla.org/firefox/probe/a11y_backplate/explore?currentPage=1&process=parent&ref=20221014215500
