### ISSUE TITLE
API unavailable: 502 Bad Gateway on /api/v1/data/

### ISSUE THREAD

**Issue by badboy** [mozilla/glam#2286]
Getting a `502 Bad Gateway` on https://glam.telemetry.mozilla.org/api/v1/data/
The server only returns this after ~30s.

Dashboard URL: https://glam.telemetry.mozilla.org/fog/probe/gmp_update_xml_fetch_result/explore?aggType=avg&aggregationLevel=version&currentPage=1&ping_type=*

**Comment by edugfilho** [comment]
seems like an intermittent problem. I just hit the url and it worked (also got the error first time I hit it)

**Comment by badboy** [comment]
Yeah, it was definitely persistent this morning. Now looks better

**Comment by edugfilho** [comment]
Since the first observation of this is from 3 days ago, I don't think this will go away permanently right now, so I'll investigate it a little further.

**Comment by edugfilho** [comment]
Looks like this metric's data adds a good amount of memory pressure :

<img width="926" alt="Screen Shot 2023-02-06 at 9 30 08 AM" src="https://user-images.githubusercontent.com/5804462/216998102-9405286c-3c5d-47cc-8ee8-6d0132d4feb3.png">

**Comment by badboy** [comment]
Is it only that one metric? Interesting.

**Comment by edugfilho** [comment]
seems like it. My Postman froze (probably oom) when I replayed the request there lol

**Comment by badboy** [comment]
Yeah, it returns quite a huge amount of data: 4.22 MB gzipped, 19.52 MB unpacked JSON.
Tried with [`cookie.banners.click.result`](https://glam.telemetry.mozilla.org/fog/probe/cookie_banners_click_result/explore?aggKey=fail&aggType=avg&currentPage=1&ping_type=*).
The request took 1.58s and returned 2.57 MB (11.80 MB unpacked).

Overall that seems like a whole bunch of data for labeled counters.

Compared to [`cookie.banners.click.handle_duration`](https://glam.telemetry.mozilla.org/fog/probe/cookie_banners_click_handle_duration/explore?aggKey=fail&aggType=avg&currentPage=1&ping_type=*), a timing distribution: 76.37 kB (500.94 kB unpacked)

**Comment by edugfilho** [comment]
what's curious to me is  for [gmp_update_xml_fetch_result release](https://glam.telemetry.mozilla.org/fog/probe/gmp_update_xml_fetch_result/explore?aggKey=cert_pin_success&aggType=avg&aggregationLevel=version&app_id=release&currentPage=1&ping_type=*) the response is way smaller

**Comment by edugfilho** [comment]
[glean_validation_pings_submitted](https://glam.telemetry.mozilla.org/fenix/probe/glean_validation_pings_submitted/explore?aggType=avg&app_id=release&currentPage=1) also spins for a while and then says there was a server error.

I did some investigation on this and found a higher number of buckets compared to legacy_telemetry metrics. That, coupled with the amount of keys in `glean_validation_pings_submitted` and `gmp_update_xml_fetch`, increases the payload size for the metrics significantly, which is probably slowing down backend processing of that payload.

**Comment by edugfilho** [comment]
This seems to have been fixed after GLAM started reading from BQ instead of Postgres. It was one of the assumptions of the change that queries that would take longer to run (>10s) would be quicker on BigQuery.

The 30s mentioned in the first message is a timeout imposed by the Load Balancer, which keeps the HTTP connection while waits for an answer from the Kubernetes pod. 
So I think what's happening now is: BigQuery returns data faster, which gives the server more time to crunch through it and respond back to the Load Balancer within the 30s deadline.
