### ISSUE TITLE
Migrate to Sapper

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#229]
Migrate to [Sapper](https://sapper.svelte.dev/) so that we can take advantage of its routing features, enforced project structure, and more. The routing features of Sapper are particularly important as they will help us to fix the back button.

**Comment by hamilton** [comment]
This will probably require (1) refactoring a bit of the layout components used in GLAM (I just merged a PR this evening that does this) and (2) organizing the code in terms of routes. I'm happy to take these parts on since they will be required for this migration.

**Comment by openjck** [comment]
Sure, I'm happy to collaborate. Is there anything else other than (1) and (2)?

**Comment by openjck** [comment]
We talked about this in our 1:1 today. Hamilton is going to reorganize the code but I'll take care of actually installing/configuring/using Sapper.

We want the paths to be: 
/<product_name>/<probe_name>/<view_name>/?query_string

The store should match the path and the query string in a two-directional fashion. That is, updating the query string should cause the store to update. Right now, it only works the other way around.

**Comment by hamilton** [comment]
@openjck I merged the reorg refactor, so work on this issue should be unblocked now.

**Comment by openjck** [comment]
We found that adding Sapper was much more difficult than we anticipated, in particular because it conflicted with our current approach to state management. Instead, we're going to implement client-side routing in #248.
