### ISSUE TITLE
Client counts on uri_count are suspiciously low

### ISSUE THREAD

**Issue by chutten** [mozilla/glam#2348]
**Describe the bug**
Per https://glam.telemetry.mozilla.org/fog/probe/browser_engagement_uri_count/explore?aggType=sum&app_id=release&currentPage=1&ping_type=*&timeHorizon=QUARTER the client counts (less than a handful) of the number of uris loaded (something we'd expect nearly every client to report nearly every day) are suspiciously low.

**To Reproduce**
1. Go to https://glam.telemetry.mozilla.org/fog/probe/browser_engagement_uri_count/explore?aggType=sum&app_id=release&currentPage=1&ping_type=*&timeHorizon=QUARTER

**Expected behavior**
Millions of users

**Comment by Iinh** [comment]
Related to #2003

**Comment by Iinh** [comment]
Fixed after https://github.com/mozilla/bigquery-etl/pull/3933.
