### ISSUE TITLE
Add product to API call in frontend

### ISSUE THREAD

**Issue by robhudson** [mozilla/glam#244]
Could we update the API query to include a product key?

E.g.
```
        {
            "query": {
                "product": "desktop",
                "channel": "nightly",
                "probe": "gc_ms",
                "aggregationLevel": "version"
            }
        }
```

At the moment the back-end will ignore this, but we will update this soon.

**Comment by hamilton** [comment]
We should add this soon so we can unlock Fenix probes.

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?
