### ISSUE TITLE
https://glam.telemetry.mozilla.org/firefox/probe/a11y_instantiated_flag/explore?currentPage=1 fails to load

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/glam#2643]
I get "Oh no! The server encountered an error." instead.

**Comment by edugfilho** [comment]
I'm getting a 404 instead. However, changing process to `parent` shows data. Can you confirm?

**Comment by jrmuizel** [comment]
Yep changing to parent gives the data. Can the error page perhaps be improved to suggest that?

**Comment by jrmuizel** [comment]
Or default to the process that has data when searching for a probe?

To get to the 404, I did a search for a11y_instantiated_flag from https://glam.telemetry.mozilla.org/?currentPage=1
