### ISSUE TITLE
"TypeError: can't convert undefined to object" on homepage

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#269]
On our dev server, several people are seeing the following error related to line 51 of *Proportion.svelte*:

TypeError: can't convert undefined to object

**Comment by hamilton** [comment]
This is likely due to pathological data conditions on the server. This said, we should use this as an excuse to catch these types of errors.

**Comment by spasovski** [comment]
part of the solution was merged https://github.com/mozilla/glam/pull/275 the rest will be covered by the JS validator functions
