### ISSUE TITLE
Have cumulative mode for distribution view 

### ISSUE THREAD

**Issue by Iinh** [mozilla/glam#2691]
Recently we added a new distribution view that's a more detailed version of the violin plot, however there is no cumulative view for it yet. This improvement has been requested by some users.

**Comment by edugfilho** [comment]
Is this a must before we make GLAM public?

**Comment by edugfilho** [comment]
> Is this a must before we make GLAM public?

During the Data Tools WG meeting today we received signal from Rob that it's not a must but we should try.
