### ISSUE TITLE
Review the metric list

### ISSUE THREAD

**Issue by Iinh** [mozilla/glam#2700]
We should consult legal and other relevant parties to determine if the metrics currently displayed in GLAM (excluding search metrics) are suitable for public viewing. Also we need to ensure that they are at TMO parity.

**Comment by edugfilho** [comment]
[This spreadsheet ](https://docs.google.com/spreadsheets/d/1wNvSpycbzMkN84SupeYACPGtrAMX8nZihcMWcpO0pfU/edit?gid=1878874974#gid=1878874974) was used to get classify and get approval on the list of metrics to be filtered out
