### ISSUE TITLE
Show a spinner while authentication is being processed

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#272]
Inspired by [this comment](https://github.com/mozilla/glam/pull/261#discussion_r385954573). We should show a spinner while authentication is being processed. I've seen the same behavior that Hamilton is seeing. When auth0 redirects back to GLAM, there can be a few moments where `code` and `state` are in the URL before `handleRedirectCallback` is run.

**Comment by hamilton** [comment]
@openjck going to assign this to you for now, since you're closest to it

**Comment by hamilton** [comment]
I would also maybe suggest that we show as much of the app (header, empty body, etc) as possible so users aren't jarred by the experience.
