### ISSUE TITLE
create a product-keyed config.js file

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#276]
Once we support multiple products, we will need to make it easy to change the set of menus for each. For instance, our mobile products might require options around selecting manufacturer, while our desktop browser should allow useres to select process type.

This will be vital in preparing for Glean products in the next month or so.

A sketch of the solution would look like this:

(1) a `config.js` file that includes all the products – key, label, and menu options
(2) the store will need to capture all the product-specific options (like `channel`, `process`, or `manufacturer` into a `productOptions` object.
(3) changing the product should set the menus & `productOptions` part of the store.

More details in the code snippet below:

```javascript
// config.js
const products = {
  fenix: {
    key: 'fenix',
    label: 'Fenix for Android',
    options: [
      {
        key: 'channel',
        label: 'Channel',
        values: [
          {
            key: 'beta',
            label: 'Beta',
            description: 'whatever',
          },
          ...
        ],
      },
      { 
        key: 'manufacturer',
        ...
      }
    ],
    validators: [
      noDuplicates,
      (data) => data.length ? oaidfnosidfndosifnad
    ]
  },
  firefoxLegacyTelemetry: {
    ...
    options: [
      {
        key: 'process',
        ...
      }
    ]
  }
};

// down in the store
const store = {
  product: 'fenix',
  productOptions: {
    channel: "beta",
    manufacturer: 'samsung',
  }
  ...
}

// when you chnage the product ...
store.product => 'firefox'

// ... the productOptions set changes accordingly.
store = {
  product: 'firefox',
  productOptions: {
    channel: 'beta',
    process: 'content'
  }
}
```

**Comment by acmiyaguchi** [comment]
For the Glean products, some of these values are not enumerated in static configurations anywhere. For example, the list of channels in fenix may take on the values `fenixProduction` and `release` which can be inferred by looking at the aggregates:

```sql
SELECT
  DISTINCT channel
FROM
  `glam-fenix-dev`.glam_etl_dev.fenix_client_probe_counts_extract_v1
```

Should the process of building these per-product configurations include mining the aggregates for options, or is this something that will need to be provided up front before metrics are discoverable?
