### ISSUE TITLE
GLAM breaks when Normalization none is selected for a probe that doesn't have non-normalized data

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glam#2777]
Spin off of https://github.com/mozilla/glam/issues/2774
STR:

    Navigate to https://glam.telemetry.mozilla.org/
    select telemetry probe 'gc_minor_us'
    select channel 'release'
    select normalization 'none'

Result:

The site becomes unresponsive. The console reports the following exception was thrown:

```Uncaught (in promise) TypeError: n[(n.length - 1)][Gn(...)].map is not a function
    l QuantileExplorerView.svelte:77
    update QuantileExplorerView.svelte:89
    xt index.mjs:1343
    _t index.mjs:1307```

**Comment by edugfilho** [comment]
This probe doesn't have enough client count on release to provide for accurate statistics. GLAM was never supposed to have collected release data for the probe in question, due to the low client counts. The reason why there are two builds there is because those builds were aggregated before a [better client count filtering was put in place for release](https://github.com/mozilla/glam/issues/github.com/mozilla/glam/issues/1575).

Considering that, I removed the few data points for that probe in `release` from the dataset, which is now making GLAM display a "Not Found" message when the probe is selected for release instead of breaking.

**Comment by jonco3** [comment]
I checked and this now works for the gc_minor_us probe. But this still affects other probes.

For example, if I look at gc_mark_ms and select channel 'release' and then then normalization 'none', the following exception is thrown:

```
Uncaught (in promise) TypeError: n[(n.length - 1)][Gn(...)].map is not a function
    l https://glam.telemetry.mozilla.org/static/bundle.js:9
    update https://glam.telemetry.mozilla.org/static/bundle.js:9
    xt https://glam.telemetry.mozilla.org/static/bundle.js:1
    _t https://glam.telemetry.mozilla.org/static/bundle.js:1
```

Would it be possible to check for this in the front end?

**Comment by edugfilho** [comment]
Thanks @jonco3 for showing that wasn't an isolated issue. I'm re-opening the ticket.

**Comment by Iinh** [comment]
I can take this work @edugfilho
