### ISSUE TITLE
https://glam.telemetry.mozilla.org/firefox/probe/gfx_linux_window_protocol/explore?currentPage=1 shows no data

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/glam#2778]
Querying manually on stmo works fine:
```
SELECT
  COUNT(DISTINCT client_id) AS nr_clients,
  payload.processes.parent.scalars.gfx_linux_window_protocol AS window_protocol,
  DATE(submission_timestamp) as date
FROM
  telemetry.main_1pct
WHERE
  environment.system.os.name = "Linux"
  AND submission_timestamp >= TIMESTAMP("2024-01-01")
GROUP BY
  date,
  window_protocol
ORDER BY date ASC
```

**Comment by Iinh** [comment]
Hi @jrmuizel, thanks for reporting! The reason why the data is not showing is that we currently do not aggregate string scalars (only `uint` scalars are available right now in GLAM). There is definitely room for improvement in the UI though, e.g. we could provide better explanations for why this specific metric type is not displaying data.
