### ISSUE TITLE
Use Counter incorrectly says metric not supported in looker

### ISSUE THREAD

**Issue by mgaudet** [mozilla/glam#2808]
As an example, [use.counter.doc.js_wasm_legacy_exceptions](https://glam.telemetry.mozilla.org/fog/probe/use_counter_doc_js_wasm_legacy_exceptions/explore?aggType=avg&currentPage=1&ping_type=*) says the metric isn't available in Looker.

But the [GLAM dictionary links directly to Looker](https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/metrics/use_counter_doc_js_wasm_legacy_exceptions)

which works.

**Comment by Iinh** [comment]
Thanks for reporting @mgaudet. I'll open a fix for this.

**Comment by Iinh** [comment]
After talking to the team, as GLAM is going to be open for public usage soon and Looker being an internal source, we've decided it's better for now to have the Glean Dictionary as the main source for Looker links. We'll remove the Looker links for now. Please let us know if you think this is necessary in GLAM.
