### ISSUE TITLE
Can we apply events_stream performace improvements to GLAM ETL?

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glam#2840]
Following @BenWu 's improvement to `events_stream`'s queries in https://github.com/mozilla/bigquery-etl/pull/5659 we should see if we can: 
* Replace JS UDFs with SQL. JS scales very poorly with the size of the input, so we might have some low hanging fruits there performance-wise. 
* Move computations before cross joins so they process less data (where possible)

**Comment by BenWu** [comment]
Some notes re:js udfs, it would be good to see the maximum improvement we can get from replacing the js udfs before committing too much time into it.  One quick way is to just replace the udfs with stub udfs that do very little and see how much slot time reduces.

From a quick look at `mozfun.glam`, the js udfs are:
- histogram_cast_json
- histogram_generate_exponential_buckets
- histogram_generate_functional_buckets
- histogram_generate_linear_buckets
- histogram_generate_scalar_buckets
- percentile

Looking at where these are used, I wouldn't expect a huge improvement from replacing these but I think it's low-effort enough to try.

I created a sample pr with the three of the fairly trivial conversions at https://github.com/mozilla/bigquery-etl/pull/5689
