### ISSUE TITLE
Upgrade all NPM dependencies

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#298]
I've run into a couple of issues that have made me wonder whether updating our dependencies would fix the issue, for example the `stop is not a function` error which appears sporadically. These can be difficult to debug.

To take one more thing out of the equation, especially because we're using some relatively new tools, I'd like to help us keep our dependencies up-to-date. There's a pull request open for this (#145) but I think it would be easier for us to update and test one at a time for now. I'll do that and tag them with this issue's number.

**Comment by openjck** [comment]
In progress. I've been testing and merging dependabot PRs.

**Comment by robhudson** [comment]
Closing since dependabot covers this
