### ISSUE TITLE
visual improvement: let's just label these axes, shall we?

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#302]
People will be invariably confused by the lack of labels on the axes. So we should add them. It's the right thing to do.

**Comment by KaustubhKumar05** [comment]
Hello! I would like to work on this issue. Could you please elaborate?

**Comment by rafrombrc** [comment]
We can do this for Glean probes, but I don't know if there's a way to reliably get Y axis units for desktop telemetry probes.

**Comment by edugfilho** [comment]
Closing this as a duplicate of https://github.com/mozilla/glam/issues/638. Keeping that one because it has more context
