### ISSUE TITLE
accommodate engineers who tile their browser windows and look at tiny viewports

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#343]
Since the beginning of GLAM development, we knew that we were not going to design for mobile. We had conversations about _not_ accommodating whatever weird screen sizes people have. It would, however, be advantageous to make sure we accommodate engineer browser windows that are very small in _some_ ways. 

I would argue we should not design for less than 900px. Given that, I can see the work here being:

- fix the search bar to be dynamically-sized after a certain breakpoint
- un-round the corners on the body when < 1200px
- figure out what to do with menus in small environment. Maybe the search bar collapses so the menus on the top right are always visible.
- @spasovski you and I had chatted about this a while ago, but we could also move the details pane to be below the body when the window is small. Might be time to revisit that.

<img width="1161" alt="Screen Shot 2020-03-23 at 3 03 02 PM" src="https://user-images.githubusercontent.com/95735/77351707-5eb91380-6cfb-11ea-8e35-0dc9a81d3351.png">

**Comment by hamilton** [comment]
Generally, I'm fine making readers scroll if they use tiny windows. The toolbar tweaks seem like a good idea regardless

**Comment by hamilton** [comment]
another option with the details pane is to make it a togglable side part, as we had in the original version of GLAM, after the < 1200px breakpoint

**Comment by edugfilho** [comment]
I'm closing this as part of a cleanup effort. Seems like all concrete action items of this issue have been tackled. 
There are things to figure out, looks like the topic lost traction and we've lost context on the convo since the members involved in it left the company. Besides, users haven't voiced any concerns regarding this.
