### ISSUE TITLE
add description for aggregation method (eg summed-histogram) somewhere in the frontend

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#346]
A question flagged by data science pre-emptively – firefox engineers might make assumptions on what kind of aggregation method we use. For `summed-histogram`, we should provide a clear description of the aggregation method.

**Comment by rafrombrc** [comment]
Points to a lack of documentation of the overall GLAM aggregation methodology... we should dig up and/or generate any docs we can to describe this and at least provide a link from the UI to these docs.

**Comment by alekhyamoz** [comment]
1. Show aggregation method on front-end (if the method is not known, ETL needs to pass the data along for app to access)
2. Aggregation method is linked to another page what the method means (DTMO reference)

**Comment by alekhyamoz** [comment]
The aggregation method information is being sent over by the ETL in the 'client_agg_type' column.
