### ISSUE TITLE
'JSON.parse' error for memory_heap_allocated probe against 'Release' channel

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/glam#361]
This URL:

https://glam-stage.bespoke.nonprod.dataops.mozgcp.net/firefox/probe/memory_heap_allocated/explore?activeBuckets=%5B%5D&aggregationLevel=build_id&channel=release&os=Windows&process=content&proportionMetricType=proportions&timeHorizon=MONTH&versions=%5B%5D&visiblePercentiles=%5B95%2C75%2C50%2C25%2C5%5D

is showing me this error message:

JSON.parse: unexpected character at line 2 column 1 of the JSON data

**Comment by hamilton** [comment]
On the staging server this reports a 403, while localkly it reports a 500:

```TypeError at /api/v1/data/,int() argument must be a string, a bytes-like object or a number, not 'NoneType'```

**Comment by robhudson** [comment]
Removes Django's CSRF middleware (among a few other things we aren't using):
https://github.com/mozilla/glam/commit/fa3651de699b5a4bc11a001f430cee73821dbe3f

**Comment by hamilton** [comment]
This looks like it was fixed on `dev`. Closing now.
