### ISSUE TITLE
Make glam frontend available from the docker container

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/glam#380]
When I run `make up` and navigate to `localhost:8000`, I expect to be able to see the front page. Instead I get a blank screen and the following messages in the console.

```
server_1  | [01/Apr/2020 21:38:48] "GET / HTTP/1.1" 200 404
server_1  | Not Found: /static/bundle.js
server_1  | Not Found: /static/bundle.css
server_1  | [01/Apr/2020 21:38:48] "GET /static/global.css HTTP/1.1" 304 0
server_1  | [01/Apr/2020 21:38:48] "GET /static/bundle.css HTTP/1.1" 404 2564
server_1  | [01/Apr/2020 21:38:48] "GET /static/bundle.js HTTP/1.1" 404 2561
server_1  | [01/Apr/2020 21:38:48] "GET /static/fonts/inter/Inter-upright.var.woff2 HTTP/1.1" 304 0
```

I think it would be useful to be able to run the frontend without having to install any of the node dependencies, at least for viewing changes to the backend.

**Comment by robhudson** [comment]
When GLAM moves to the nginx based auth0 proxy this will be easier, as currently local development with auth0 is configured for localhost:5000. The Dockerfile does build the front-end by not when using docker-compose b/c of the docker-compose config. This is how dev/stage work, so getting localhost to work in this way also should be possible. I would like this as well and will circle back to this after auth0 changes.

**Comment by robhudson** [comment]
This is now possible and docs updated.
