### ISSUE TITLE
the GLAM API needs to be re-formulated to return tidy data

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#394]
When we first started work on this project, there was quite a bit discussion on what the API response should be. I made a mistake in not pushing for that which I've seen from experience – tidy data is always, always the preferred structure in almost every single case, as it reduces the burden on the frontend / visualization layer.

Fast forward to months later, and there is a considerable amount of awkward data transformation that has to happen in the browser in GLAM that is hard to refactor. Much of this is untested. Instead of refactoring it and writing tests, I would like to propose that we go with the original suggestion to produce a [tidy data](https://vita.had.co.nz/papers/tidy-data.pdf) set instead of what we have, and write tests around that. This is a standard across data engineering already in many projects, including GUD. Moving the API response to work solely for GLAM will be a huge gain to everyone who might use the API for other purposes down the line as well.

**Comment by robhudson** [comment]
Is this still required?

**Comment by robhudson** [comment]
I'm going to call this done as part of the transpose work. While it's not "tidy data", we did make the JSON response schema more flat and more representative of a single row of data.
