### ISSUE TITLE
replace this "invalid request" error message with a "no data available"

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#396]
I think we're buring the lede on this error message

<img width="980" alt="Screen Shot 2020-04-09 at 7 23 53 AM" src="https://user-images.githubusercontent.com/95735/78905635-27ed3800-7a33-11ea-8a81-13fc3d9bf78d.png">

**Comment by spasovski** [comment]
resolved via https://github.com/mozilla/glam/pull/404
