### ISSUE TITLE
handle firefox desktop probes w/o any process

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#416]
It's unclear how we should handle cases where for Firefox Desktop a probe has no processes associated with it. Some cases with no processes in the probe info service:

```
a11y_update_time - no processes
aboutcrashes_opened_count - no processes
about_accounts_content_server_loaded_rate - no processes
about_accounts_content_server_loaded_time_ms - no processes
about_accounts_content_server_load_started_count - no processes
audio_track_silence_proportion - content
battery_status_count - no processes
browserprovider_xul_import_history - no processes
browserprovider_xul_import_time - no processes
cache_service_lock_wait_mainthread_nscacheservice_leaveprivatebrowsing - no processes
cache_service_lock_wait_mainthread_nsdiskcachedevicedeactivateentryevent_run - no processes
cache_service_lock_wait_mainthread_nsdiskcachemap_revalidation - no processes
cache_service_lock_wait_mainthread_nsdiskcachestreamio_closeoutputstream - no processes
cache_service_lock_wait_mainthread_nsdiskcachestreamio_write - no processes
cache_service_lock_wait_mainthread_nsdoomevent_run - no processes
cache_service_lock_wait_mainthread_nsevictdiskcacheentriesevent_run - no processes
cert_validation_library - no processes
checkerboarded_csspixels_ms - no processes
compartment_adopted_node - no processes
```

/cc @robhudson – I think some Probe API work might have to be done here.

**Comment by robhudson** [comment]
Hamilton and I discussed this and we are seeing 2 types of 404 here:

1. Old, inactive probes that have no data in the glam ETL dataset and never will. These are probes that expired long ago.
2. Inactive probes that have no current data but may have some historical data in GLAM.

For both, the `inactive` flag will signal that there is no data in glam for this probe and we can display an alternate style 404 page to signify this probe is no longer recording.

For the probes of type 1, it would be nice if the search would not surface these.
