### ISSUE TITLE
import graph-paper optionmenu-like functionality into the dimension selectors

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#442]
The dimension selectors don't quite conform to the optionmenu component, but it's not that far off. A few lateral changes using the same funcitons should accomplish the same thing. This includes:

- accessibility – tab over menu, esc key closes, click-away events are not well-designed as it is now
- styling – the option menu functionality is a bit clunky

**Comment by openjck** [comment]
I'd be happy to take this on. Are the dimension selectors the OS / Channel / etc. selectors?

**Comment by hamilton** [comment]
thanks, and yep, it's those ones on the top right above the body.

**Comment by robhudson** [comment]
Pretty sure this was done as part of the udgl removal. Reopen if I misunderstood the issue.
