### ISSUE TITLE
import @graph-paper/datagraphic, @graph-paper/elements, and @graph-paper/guides into GLAM

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#444]
We have a few minor changes that will need to be done soon that requires for us to do the investment of migrating all the data graphics to `graph-paper`.

**Comment by imskr** [comment]
Can I work on this?

**Comment by hamilton** [comment]
sorry @imskr, work has already begun on this and it would require a pretty thorough knowledge of a part of our stack that isn't easily accessible
