### ISSUE TITLE
move the client counts to where the current client comparison chart is

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#448]
The tiny client count comparison chart is near-useless (this is my hunch, but I think it's accurate). We should move the client counts to be more adjacent to this, esp. to keep confusion to a minimum.

![Screen Shot 2020-04-28 at 4 42 24 PM](https://user-images.githubusercontent.com/95735/80548315-83924d80-896f-11ea-9f9a-3d8149594e8a.png)

**Comment by edugfilho** [comment]
The value here is unclear.
