### ISSUE TITLE
Add 'get shortlink' link

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/glam#458]
The original TMO dashboard has a 'get shortlink' button that emits a much shorter link to the current view for sharing, Vicky missed that in GLAM.

**Comment by hamilton** [comment]
frank linked to the implementation here: https://github.com/mozilla/telemetry-dashboard/blob/76743c5a99a664c94882c29868bb73788c33ea6b/new-pipeline/src/dashboards.js#L148

**Comment by edugfilho** [comment]
We won't prioritize this right now. We can reopen this if it becomes relevant in the future.
