### ISSUE TITLE
If there is insufficient data volume for a probe, we need to return this information to the frontend

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#468]
I know we are filtering out builds / versions with < 1k clients. We do not, however, have a way of telling the frontend that this is the case.

**Comment by hamilton** [comment]
After the data transpose work is finished, we might lift the < 1k clients requirement, which would effectively fix this issue.

**Comment by robhudson** [comment]
> After the data transpose work is finished, we might lift the < 1k clients requirement, which would effectively fix this issue.

We did reduce this value 100. Closing.
