### ISSUE TITLE
allow data endpoint URL to be defined in a config

### ISSUE THREAD

**Issue by spasovski** [mozilla/glam#487]
We wish to be able to bypass the local DB and go straight to dev or stage when needed.

**Comment by spasovski** [comment]
I did some investigation into this (can open the draft PR if desired) but it ultimately didn't work since the local auth token is not something we can send to stage/dev. We'll need to investigate other avenues to accomplish this.

**Comment by hamilton** [comment]
got it. Thanks for checking!
