### ISSUE TITLE
specify what "all time" means (in parens)

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#540]
The explore view has an "all time" button, which it is unclear what this means.

**Comment by openjck** [comment]
This came up in Eric's user interview. :smiley:

**Comment by openjck** [comment]
This is also [goodui.org rule 68](https://goodui.org/#68). I have to say, I think Hamilton did a great job of this already by using tooltips extensively.

<img width="968" alt="Screen Shot 2020-06-12 at 11 00 49 PM" src="https://user-images.githubusercontent.com/933396/84558436-db5afd00-ad00-11ea-9ee4-5e68b515d4e7.png">

**Comment by robhudson** [comment]
This was updated recently and explains what "All" means in the tooltip
