### ISSUE TITLE
replace the copied icons w/ Photon icons

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#56]
Usually when I get to building, I just download the material design icons I need (simple things like arrows, magnifying glass for search, etc.), but it would be a good policy going forward to use the  [photon icon](https://design.firefox.com/icons/viewer/#) equivalent for each one.

This should be a very straightforward task that requires:

(1) finding the photon icon and getting the svg for it
(2) replacing the current svelte icon components (which are just svg + a prop for size, plus ensuring that `fill: currentColor` is set in the style of the svg)
(3) making sure the new icons work the same in terms of spacing, etc.

**Comment by Siddharth1698** [comment]
Shall I work on this.
