### ISSUE TITLE
Replace components and other code (helper files, etc.) with their graph-paper counterparts

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#562]
I *really* want to avoid a situation where we have diverging copies of code. Merging those divergent changes later would be much, much more annoying than preventing divergence from occurring in the first place.

Wherever we can, we should rip out local copies of components and other code (helper files, etc.) and replace them with their graph-paper counterparts.

Some files that this can be applied to (please update/correct this list as needed):

- [ ] Button.svelte
- [ ] ButtonGroup.svelte
- [x] DataGraphic.svelte
- [ ] BoxPlot.svelte
- [x] Heatmap.svelte
- [x] Line.svelte
- [x] Point.svelte
- [ ] VerticalErrorBar.svelte
- [x] AxisTick.svelte
- [x] Axis.svelte
- [x] AxisLine.svelte
- [x] AxisLabel.svelte
- [x] RightAxis.svelte
- [x] BottomAxis.svelte
- [x] LeftAxis.svelte
- [x] TopAxis.svelte
- [ ] MarginText.svelte
- [ ] Marker.svelte
- [ ] icons/Help.svelte
- [ ] icons/Search.svelte
- [ ] icons/Cancel.svelte
- [ ] icons/Table.svelte
- [ ] FloatingMenu.svelte
- [ ] MenuList.svelte
- [ ] MenuListItem.svelte
- [ ] Portal.svelte
- [x] tooltip.js
- [x] float-placement.js
- [x] window-functions.js

**Comment by openjck** [comment]
I'm sorry if this is verbose. I could have also just written something brief about ripping out udgl. But I thought the checklist would help us keep this work organized.

**Comment by robhudson** [comment]
This has been completed
