### ISSUE TITLE
scalar y scales should probably always be logarithmic

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#574]
Once @emtwo's scalar bucket changes land, it would be advantageous to change the scaling of the y-axis to always be logarithmic. Here's a simple recipe for making the axis look good:

(1) always use `log` scaling for scalars
(2) let's go beyond just using hte percentile ranges. take the 95th percentile max value, raiise it one order of magnitude, and then set that as `yMax`

**Comment by edugfilho** [comment]
Looking at the charts it seems like we need to consider working on the ceiling ranges to show certain charts better such as for [a11y_hcm_foreground](https://glam.telemetry.mozilla.org/firefox/probe/a11y_hcm_foreground/explore?channel=release&currentPage=1&process=parent&ref=20220718155818&timeHorizon=ALL&visiblePercentiles=%5B99.9%2C99%2C95%2C75%2C50%2C25%2C5%2C1%5D). However we don't think changing the Y scale to log is necessarily the way to go.
