### ISSUE TITLE
color swatches no longer center-align in quantile button group

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#598]
cc @openjck 

On stage, the color swatches are vertically centered with the text. On `master`, however, the swatches are aligned on the baseline, not centered.

<img width="1046" alt="Screen Shot 2020-06-09 at 8 56 59 PM" src="https://user-images.githubusercontent.com/95735/84225496-20c6c280-aa94-11ea-9b61-599c12829c44.png">

This issue also occurs iin proportion charts w < 10 categories.

**Comment by openjck** [comment]
This should definitely be addressed, but we haven't pushed the OptionMenu to stage yet:

https://glam-stage.bespoke.nonprod.dataops.mozgcp.net/firefox/probe/gc_reason_2/explore?activeBuckets=%5B%2236%22%2C%2247%22%2C%2215%22%2C%2240%22%2C%2231%22%2C%2252%22%2C%2249%22%2C%2238%22%2C%2227%22%2C%225%22%5D&aggregationLevel=build_id&channel=nightly&os=Windows&process=content&proportionMetricType=proportions&timeHorizon=MONTH&visiblePercentiles=%5B95%2C75%2C50%2C25%2C5%5D

**Comment by openjck** [comment]
Oh wait nevermind
