### ISSUE TITLE
Full-screen graphs

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#621]
In her user interview, Vicky mentioned that it would be nice if there were a way to expand certain charts, like the _Percentile_ chart, to take up the full screen.

**Comment by rafrombrc** [comment]
Doing this as a modal overlay (like the 'view sql query' window) wouldn't be a lot of work, is worth looking into.

**Comment by edugfilho** [comment]
Done in https://github.com/mozilla/glam/pull/2488
