### ISSUE TITLE
Make it easier to select vertical markers as reference points

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#623]
In her user interview, Vicky mentioned that it would be nice if she could more easily select a release as a reference point, rather than trying really hard to get it right by lining up her mouse pointer just right.

One common user interface pattern which might work here is to make the vertical hover line "snap" to releases, as if magnetically, so that it's easier to select release markers as reference points.

Here's an example of this UI pattern being used in macOS:

![Jun-12-2020 22-52-10](https://user-images.githubusercontent.com/933396/84558248-6b984280-acff-11ea-8724-9318f318e443.gif)

**Comment by edugfilho** [comment]
Getting this right would require a fair amount of user research and investigation in order to avoid providing false information. In the meantime this is not a big enough issue to prioritize.
