### ISSUE TITLE
Re-arrange hover/reference columns based on their left-to-right order

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#628]
This one is up for discussion, but based on our user interview with Eric (and my personal experience, for whatever it's worth), we may want to consider dynamically swapping the *Hover* and *Reference* columns in tables and the violin chart based on which appears first in the data.

For example, if the hover point appears first in the data, we could show the *Hover* column first. If the reference point appears first in the data, we could show the *Reference* column first.

Here's a quote from Eric about this:

“On the [Percentiles] visualization, the reference point precedes the hover point, on the compare, the hover point is on the left and the reference point is on the right, so that was a little disorienting. Similarly, the summary chart values are opposite of what I’d expect.”

**Comment by Iinh** [comment]
We just had a user interview with Bas recently and he also asked for this feature. Let's make it a priority for M8.

**Comment by Iinh** [comment]
Closed via #2092.
