### ISSUE TITLE
update color scheme to be more GLAM

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#70]
The current color scheme was envisioned before GLAM was the name. This task will require two tasks:

- [ ] move the primary UX color to be a purple (use [colorbox](https://www.colorbox.io/) to generate a worthwhile palette)
- [ ] move the secondary / button UX color to be a bright raspberry
- [ ] create a new set of CSS variables that are unconnected to the color value variables, allowing us to change things up easily by resetting the semantic vars instead of switching which color we use throughout the app
- [ ] tweak the color vars that exist now to work with new color palettes.

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?

**Comment by Rudresh22** [comment]
Hello, please allow me to work on this issue

**Comment by Kushagraw12** [comment]
Hi, can i take up this issue?
Thanks!

**Comment by rafrombrc** [comment]
Closing for now, UI changes to be revisited later.
