### ISSUE TITLE
network_autodial seems broken in an interesting state

### ISSUE THREAD

**Issue by spasovski** [mozilla/glam#704]
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/391260/86189436-336a6f80-bb07-11ea-8b62-eaf81faf19a8.png">

Alessio mentioned this probe is not valid so I wouldn't be concerned about it missing data but we may want to explore why it's checking the undefined process

**Comment by robhudson** [comment]
This will be taken care of with #937
