### ISSUE TITLE
Infinite authentication loop

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#717]
Some users are reporting infinite authentication loops. I've had some difficulty reproducing it. It could be related to browser add-ons like uBlock. One user reported that it happened to them normally, but not when in private browsing mode.

Davor might be a good person to help test this, as he's currently having issues logging in locally in general.

The loop has been reported with the following URL, but may also affect others:

https://glam-dev.bespoke.nonprod.dataops.mozgcp.net/firefox/probe/device_reset_reason/explore?activeBuckets=%5B%222%22%2C%223%22%2C%221%22%2C%224%22%2C%220%22%2C%225%22%2C%226%22%2C%227%22%2C%228%22%2C%229%22%5D&aggregationLevel=build_id&channel=nightly&os=Mac&process=content&proportionMetricType=proportions&timeHorizon=MONTH&visiblePercentiles=%5B95%2C75%2C50%2C25%2C5%5D

**Comment by openjck** [comment]
This is a tricky one. I can't seem to reproduce it, but I totally believe that something is wrong. There was another GitHub issue about this not long ago which we also had trouble reproducing and which we ultimately closed. I think I'm going to try to borrow some time from Davor to look at this with me over screen-share, since he's reported having trouble signing in locally.

**Comment by openjck** [comment]
My PR #736 didn't fix the issue for Davor, but, thankfully, I can now reproduce this on my own machine (Linux-based) using Firefox Nightly and hitting localhost.

**Comment by openjck** [comment]
I think this happens because GLAM is not currently hosted on a mozilla.com domain. It also seems to be related to ETP. Steven Englehardt opened a [bug against core](https://bugzilla.mozilla.org/show_bug.cgi?id=1654153) about this issue, but we can probably also do something to fix this on our end. Steven pointed to the [cross-origin authentication documentation for Auth0](https://auth0.com/docs/cross-origin-authentication) in particular.

There is a workaround for this which involves disabling ETP on the domain being used (e.g., the GLAM staging domain if the GLAM staging site is being used). Because the redirect is automatic, I find that this is easier to do if throttling is first enabled in Developer Tools.

**Comment by openjck** [comment]
My knowledge-sharing here is up-to-date. I don't have anything to add beyond the prior comment.

**Comment by robhudson** [comment]
Fixed in d7b8a453c75e6d9ebb03e49bf7ed55d9fcaa4001
