### ISSUE TITLE
configure Circle CI for frontend build / test / linting

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#73]
Before we moved to tag releases, it'll be good to enforce some discipline to frontend development. For the frontend specifically, we should configure Circle CI to:

- build: check to see if GLAM builds properly
- test: test coverage should be a priority, where appropriate
- lint: having linting rules helps us take care of 95% of low-level style disagreements

**Comment by rbrishabh** [comment]
Hey! I would like to take this up.

I don't have much knowledge about configuring Circle CI, but I'd love to look into this.
I will start by doing some google searches, I'll ask you if I get stuck.

Thanks!

**Comment by hamilton** [comment]
@rbrishabh thanks for the offer! We actually have a dev working on this already, and I forgot to assign this issue to him, so we don't need any help on this.

**Comment by rbrishabh** [comment]
Alright!

**Comment by robhudson** [comment]
The CircleCI config has been set up for the backend. What's left to do is adding frontend testing and linting to it.
