### ISSUE TITLE
Incorrect / superfluous 404 for dns_renewal_time_for_ttl

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#792]
## Steps to reproduce

1. Load the homepage
2. Open the console
3. Search for *dns_renewal_time_for_ttl*
4. Click it

## Result

There's a 404 in the console, even though the data loads. This didn't happen before #781 landed.

**Comment by robhudson** [comment]
I noticed this also. It's when the probe doesn't have data for the currently selected process.

In the network panel the order of events is:
1. a request to `api/v1/data` with currently chosen params that returns a 404.
2. a request to probe-search with an exact match query that fetches the probe data, which likely contains the `seen_in_processes` info for the request below.
3. a request to `api/v1/data` with the updated process that then returns a 200

**Comment by robhudson** [comment]
I think this is expected... the 404 is a signal to the front-end and it tries another process.
