### ISSUE TITLE
Verify that Google Analytics is working

### ISSUE THREAD

**Issue by openjck** [mozilla/glam#819]
Google Analytics should be working with the staging site. The code has been deployed and Blake set the relevant environment variable. However, I have not been able to verify that the data is rolling in. Even before my access began to be restricted last week, I could not see the GLAM property on Google Analytics.

I recommend following up on [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1656328) to gain access to the data and to verify that the data is rolling in.

**Comment by robhudson** [comment]
We've decided to only have GA on the production site and disabled on dev/staging. Assigning to Blake to verify this is working.

**Comment by rafrombrc** [comment]
Verified.
