### ISSUE TITLE
it is unclear whether probe.calculated.seen_in_processes is accurate

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#847]
Example probe: `checkerboard_duration`

**Comment by robhudson** [comment]
I took a look at this. The probes search import queries the GLAM data for processes per metric. I broke this down a bit more to see the channels and saw that only release has the `content` process...

```
[
  {
    "metric": "checkerboard_duration",
    "channel": "nightly",
    "processes": [
      "parent"
    ]
  },
  {
    "metric": "checkerboard_duration",
    "channel": "beta",
    "processes": [
      "parent"
    ]
  },
  {
    "metric": "checkerboard_duration",
    "channel": "release",
    "processes": [
      "parent",
      "content"
    ]
  }
]
```

Taking a look at the aggregations I'm seeing that for this specific set of data with the release channel, we are getting histograms but not percentiles, which the import considers invalid and the API returns a 404 in that case.

So the upstream GLAM data could be invalid which is where the probe-search `seen_in_processes` is being generated from.

**Comment by robhudson** [comment]
For context, the probe-search code that pulls in this is here:
https://github.com/mozilla/probe-search/blob/main/probes/management/commands/import_telemetry.py#L85

**Comment by robhudson** [comment]
It was determined that the source table from probe-search is incorrect and also that the above data is valid -- release does have valid pings for the content process while the other channels do not.

This unfortunately causes 404s if a user is switching between channels when the process is `parent`, but it's a valid 404 -- we have no data for those dimensions.

**Comment by robhudson** [comment]
This was updated to pull from the correct BQ table: https://github.com/mozilla/probe-search/commit/f7e38665cee6bd9274f581cf76d9ce5e0c6d3289
