### ISSUE TITLE
details view always seems to reload after clicking on new view button

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#848]
This appears to be a newer bug. It is mostly cosmetic and is not really a blocker to usage.

**Comment by robhudson** [comment]
Apparently this changed in f6f86b6332550d66e742448001501f6b0c3583f1 when pagejs was added for navigating between pages. I think this would take considerable re-work to only refresh the body content.

**Comment by rafrombrc** [comment]
The only thing that this obscures is the probe name, we'll make sure that shows up in the sidebar and not worry about this one.
