### ISSUE TITLE
Firefox: probe info service does not distinguish probes not available in certain channels

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#849]
I found this issue while looking at the Firefox probe `devtools_aboutdebugging_time_active_seconds`. It appears that this probe works for beta but not nightly. I can't find a way to distinguish where it is a available in the probe info service.

**Comment by robhudson** [comment]
I'm a bit confused by this one and will need to look closer at the underlying data, but one interesting thing to add is if you aggregate by version all 3 channels show up. But if you aggregate by build ID nightly shows a 404.

**Comment by rafrombrc** [comment]
We've done a lot of work to minimize the 404s when a probe doesn't have data for a given channel and/or process. Closing this for now, will open new issues on probes when needed.
